if GetBuildInfo and select(4,GetBuildInfo()) < 80000 then return end

if select(3, UnitClass('player')) ~= 7 then return end

local TJ = LibStub('AceAddon-3.0'):GetAddon('ThousandJabs8')

TJ:RegisterActionProfileList('simc::shaman::elemental', 'Simulationcraft Shaman Profile: Elemental', 7, 1, [[
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/totem_mastery
actions.precombat+=/fire_elemental
actions.precombat+=/potion
actions.precombat+=/elemental_blast
actions=bloodlust,if=target.health.pct<25|time>0.500
actions+=/potion
actions+=/wind_shear
actions+=/totem_mastery,if=buff.resonance_totem.remains<2
actions+=/fire_elemental
actions+=/storm_elemental
actions+=/earth_elemental,if=cooldown.fire_elemental.remains<120&!talent.storm_elemental.enabled|cooldown.storm_elemental.remains<120&talent.storm_elemental.enabled
actions+=/use_items
actions+=/blood_fury,if=!talent.ascendance.enabled|buff.ascendance.up|cooldown.ascendance.remains>50
actions+=/berserking,if=!talent.ascendance.enabled|buff.ascendance.up
actions+=/run_action_list,name=aoe,if=active_enemies>2&(spell_targets.chain_lightning>2|spell_targets.lava_beam>2)
actions+=/run_action_list,name=single_target
actions.aoe=stormkeeper
actions.aoe+=/ascendance
actions.aoe+=/liquid_magma_totem
actions.aoe+=/flame_shock,if=spell_targets.chain_lightning<4,target_if=refreshable
actions.aoe+=/earthquake
actions.aoe+=/lava_burst,if=(buff.lava_surge.up|buff.ascendance.up)&spell_targets.chain_lightning<4
actions.aoe+=/elemental_blast,if=spell_targets.chain_lightning<4
actions.aoe+=/lava_beam
actions.aoe+=/chain_lightning
actions.aoe+=/lava_burst,moving=1
actions.aoe+=/flame_shock,moving=1,target_if=refreshable
actions.aoe+=/frost_shock,moving=1
actions.single_target=flame_shock,if=!ticking|dot.flame_shock.remains<=gcd
actions.single_target+=/ascendance,if=(time>=60|buff.bloodlust.up)&cooldown.lava_burst.remains>0&!talent.storm_elemental.enabled
actions.single_target+=/ascendance,if=(time>=60|buff.bloodlust.up)&cooldown.lava_burst.remains>0&cooldown.storm_elemental.remains<=120
actions.single_target+=/elemental_blast,if=talent.master_of_the_elements.enabled&buff.master_of_the_elements.up&maelstrom<60|!talent.master_of_the_elements.enabled
actions.single_target+=/stormkeeper,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_target+=/liquid_magma_totem,if=raid_event.adds.count<3|raid_event.adds.in>50
actions.single_target+=/earthquake,if=buff.echoes_of_the_great_sundering.up
actions.single_target+=/earth_shock,if=talent.master_of_the_elements.enabled&(buff.master_of_the_elements.up|maelstrom>=92)|!talent.master_of_the_elements.enabled
actions.single_target+=/lava_burst,if=cooldown_react|buff.ascendance.up
actions.single_target+=/flame_shock,target_if=refreshable
actions.single_target+=/totem_mastery,if=buff.resonance_totem.remains<10|(buff.resonance_totem.remains<(buff.ascendance.duration+cooldown.ascendance.remains)&cooldown.ascendance.remains<15)
actions.single_target+=/frost_shock,if=buff.icefury.up
actions.single_target+=/icefury
actions.single_target+=/lava_beam,if=active_enemies>1&spell_targets.lava_beam>1
actions.single_target+=/chain_lightning,if=active_enemies>1&spell_targets.chain_lightning>1
actions.single_target+=/lightning_bolt
actions.single_target+=/flame_shock,moving=1,target_if=refreshable
actions.single_target+=/flame_shock,moving=1,if=movement.distance>6
actions.single_target+=/frost_shock,moving=1
actions+=/run_action_list,name=single_lr,if=level<100
]])

TJ:RegisterActionProfileList('simc::shaman::enhancement', 'Simulationcraft Shaman Profile: Enhancement', 7, 2, [[
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/potion
actions.precombat+=/lightning_shield
actions=wind_shear
actions+=/variable,name=hailstormCheck,value=((talent.hailstorm.enabled&!buff.frostbrand.up)|!talent.hailstorm.enabled)
actions+=/variable,name=furyCheck80,value=(!talent.fury_of_air.enabled|(talent.fury_of_air.enabled&((maelstrom>35&cooldown.lightning_bolt.remains>=3*gcd)|maelstrom>80)))
actions+=/variable,name=furyCheck70,value=(!talent.fury_of_air.enabled|(talent.fury_of_air.enabled&maelstrom>70))
actions+=/variable,name=furyCheck45,value=(!talent.fury_of_air.enabled|(talent.fury_of_air.enabled&maelstrom>45))
actions+=/variable,name=furyCheck35,value=(!talent.fury_of_air.enabled|(talent.fury_of_air.enabled&maelstrom>35))
actions+=/variable,name=furyCheck25,value=(!talent.fury_of_air.enabled|(talent.fury_of_air.enabled&maelstrom>25))
actions+=/variable,name=OCPool70,value=(!talent.overcharge.enabled|(talent.overcharge.enabled&maelstrom>70))
actions+=/variable,name=OCPool60,value=(!talent.overcharge.enabled|(talent.overcharge.enabled&maelstrom>60))
actions+=/auto_attack
actions+=/use_items
actions+=/call_action_list,name=opener
actions+=/call_action_list,name=asc,if=buff.ascendance.up
actions+=/call_action_list,name=buffs
actions+=/call_action_list,name=cds
actions+=/call_action_list,name=core
actions+=/call_action_list,name=filler
actions.asc=earthen_spike
actions.asc+=/crash_lightning,if=!buff.crash_lightning.up&active_enemies>=2
actions.asc+=/rockbiter,if=talent.landslide.enabled&!buff.landslide.up&charges_fractional>1.7
actions.asc+=/windstrike
actions.buffs=rockbiter,if=talent.landslide.enabled&!buff.landslide.up&charges_fractional>1.7
actions.buffs+=/fury_of_air,if=!ticking&maelstrom>22
actions.buffs+=/flametongue,if=!buff.flametongue.up
actions.buffs+=/frostbrand,if=talent.hailstorm.enabled&!buff.frostbrand.up&variable.furyCheck45
actions.buffs+=/flametongue,if=buff.flametongue.remains<6+gcd
actions.buffs+=/frostbrand,if=talent.hailstorm.enabled&buff.frostbrand.remains<6+gcd
actions.buffs+=/totem_mastery,if=buff.resonance_totem.remains<2
actions.cds=bloodlust,if=target.health.pct<25|time>0.500
actions.cds+=/berserking,if=buff.ascendance.up|(feral_spirit.remains>5)|level<100
actions.cds+=/blood_fury,if=buff.ascendance.up|(feral_spirit.remains>5)|level<100
actions.cds+=/potion,if=buff.ascendance.up|!talent.ascendance.enabled&feral_spirit.remains>5|target.time_to_die<=60
actions.cds+=/feral_spirit
actions.cds+=/ascendance,if=(cooldown.strike.remains>0)&buff.ascendance.down
actions.cds+=/earth_elemental
actions.core=earthen_spike,if=variable.furyCheck25
actions.core+=/crash_lightning,if=!buff.crash_lightning.up&active_enemies>=2
actions.core+=/crash_lightning,if=active_enemies>=8|(active_enemies>=6&talent.crashing_storm.enabled)
actions.core+=/stormstrike,if=buff.stormbringer.up
actions.core+=/crash_lightning,if=active_enemies>=4|(active_enemies>=2&talent.crashing_storm.enabled)
actions.core+=/lightning_bolt,if=talent.overcharge.enabled&variable.furyCheck45&maelstrom>=40
actions.core+=/stormstrike,if=(!talent.overcharge.enabled&variable.furyCheck35)|(talent.overcharge.enabled&variable.furyCheck80)
actions.core+=/sundering
actions.core+=/flametongue,if=talent.searing_assault.enabled
actions.core+=/lava_lash,if=buff.hot_hand.react
actions.core+=/crash_lightning,if=active_enemies>=3
actions.filler=rockbiter,if=maelstrom<70
actions.filler+=/flametongue,if=talent.searing_assault.enabled|buff.flametongue.remains<4.8
actions.filler+=/crash_lightning,if=(talent.crashing_storm.enabled|active_enemies>=2)&debuff.earthen_spike.up&maelstrom>=40&variable.OCPool60
actions.filler+=/frostbrand,if=talent.hailstorm.enabled&buff.frostbrand.remains<4.8&maelstrom>40
actions.filler+=/lava_lash,if=maelstrom>=50&variable.OCPool70&variable.furyCheck80
actions.filler+=/rockbiter
actions.filler+=/crash_lightning,if=(maelstrom>=65|talent.crashing_storm.enabled|active_enemies>=2)&variable.OCPool60&variable.furyCheck45
actions.filler+=/flametongue
actions.opener=rockbiter,if=maelstrom<15&time<gcd
]])

