local Engine = LibStub('LibSandbox-5.0'):GetSandbox('TJ5').Engine

Engine.Data = Engine.Data or {}
Engine.Data.Generated = Engine.Data.Generated or {}
Engine.Data.Generated.EquippedMapping = Engine.Data.Generated.EquippedMapping or {}

Engine.Data.Generated.EquippedMapping['ailuro_pouncers'] = { 137024, }
Engine.Data.Generated.EquippedMapping['call_of_the_wild'] = { 137101, }
Engine.Data.Generated.EquippedMapping['chatoyant_signet'] = { 137040, }
Engine.Data.Generated.EquippedMapping['cold_heart'] = { 151796, }
Engine.Data.Generated.EquippedMapping['consorts_cold_core'] = { 144293, }
Engine.Data.Generated.EquippedMapping['convergence_of_fates'] = { 140806, }
Engine.Data.Generated.EquippedMapping['denial_of_the_halfgiants'] = { 137100, }
Engine.Data.Generated.EquippedMapping['draught_of_souls'] = { 140808, }
Engine.Data.Generated.EquippedMapping['drinking_horn_cover'] = { 137097, }
Engine.Data.Generated.EquippedMapping['duskwalkers_footpads'] = { 137030, }
Engine.Data.Generated.EquippedMapping['frizzos_fingertrap'] = { 137043, }
Engine.Data.Generated.EquippedMapping['gnawed_thumb_ring'] = { 134526, }
Engine.Data.Generated.EquippedMapping['greenskins_waterlogged_wristcuffs'] = { 137099, }
Engine.Data.Generated.EquippedMapping['hidden_masters_forbidden_touch'] = { 137057, }
Engine.Data.Generated.EquippedMapping['insignia_of_ravenholdt'] = { 137049, }
Engine.Data.Generated.EquippedMapping['katsuos_eclipse'] = { 137029, }
Engine.Data.Generated.EquippedMapping['kazzalax_fujiedas_fury'] = { 137053, }
Engine.Data.Generated.EquippedMapping['koltiras_newfound_will'] = { 132366, }
Engine.Data.Generated.EquippedMapping['lady_and_the_child'] = { 144295, }
Engine.Data.Generated.EquippedMapping['lady_vashjs_grasp'] = { 132411, }
Engine.Data.Generated.EquippedMapping['luffa_wrappings'] = { 137056, }
Engine.Data.Generated.EquippedMapping['mangazas_madness'] = { 132864, }
Engine.Data.Generated.EquippedMapping['mantle_of_the_first_kirin_tor'] = { 151808, }
Engine.Data.Generated.EquippedMapping['mantle_of_the_master_assassin'] = { 144236, }
Engine.Data.Generated.EquippedMapping['mystic_kilt_of_the_rune_master'] = { 132451, }
Engine.Data.Generated.EquippedMapping['parsels_tongue'] = { 151805, }
Engine.Data.Generated.EquippedMapping['perseverance_of_the_ebon_martyr'] = { 132459, }
Engine.Data.Generated.EquippedMapping['qapla_eredun_war_order'] = { 137227, }
Engine.Data.Generated.EquippedMapping['sephuzs_secret'] = { 132452, }
Engine.Data.Generated.EquippedMapping['shadow_satyrs_walk'] = { 137032, }
Engine.Data.Generated.EquippedMapping['shard_of_the_exodar'] = { 132410, }
Engine.Data.Generated.EquippedMapping['shivarran_symmetry'] = { 141321, }
Engine.Data.Generated.EquippedMapping['smoldering_heart'] = { 116799, 151819, }
Engine.Data.Generated.EquippedMapping['the_deceivers_blood_pact'] = { 137035, }
Engine.Data.Generated.EquippedMapping['the_emerald_dreamcatcher'] = { 137062, }
Engine.Data.Generated.EquippedMapping['the_emperors_capacitor'] = { 144239, }
Engine.Data.Generated.EquippedMapping['the_first_of_the_dead'] = { 151818, }
Engine.Data.Generated.EquippedMapping['the_great_storms_eye'] = { 151823, }
Engine.Data.Generated.EquippedMapping['the_wildshapers_clutch'] = { 137094, }
Engine.Data.Generated.EquippedMapping['thraxis_tricksy_treads'] = { 137031, }
Engine.Data.Generated.EquippedMapping['umbral_moonglaives'] = { 147012, }
