local addonName = ...

local Engine = LibStub('LibSandbox-5.0'):GetSandbox(addonName).Engine

Engine.Generated = Engine.Generated or {}
Engine.Generated.EquippedMapping = Engine.Generated.EquippedMapping or {}

Engine.Generated.EquippedMapping.ailuro_pouncers = { 137024, }
Engine.Generated.EquippedMapping.chatoyant_signet = { 137040, }
Engine.Generated.EquippedMapping.convergence_of_fates = { 140806, }
Engine.Generated.EquippedMapping.denial_of_the_halfgiants = { 137100, }
Engine.Generated.EquippedMapping.draught_of_souls = { 140808, }
Engine.Generated.EquippedMapping.drinking_horn_cover = { 137097, }
Engine.Generated.EquippedMapping.duskwalkers_footpads = { 137030, }
Engine.Generated.EquippedMapping.frizzos_fingertrap = { 137043, }
Engine.Generated.EquippedMapping.gnawed_thumb_ring = { 134526, }
Engine.Generated.EquippedMapping.greenskins_waterlogged_wristcuffs = { 137099, }
Engine.Generated.EquippedMapping.hidden_masters_forbidden_touch = { 137057, }
Engine.Generated.EquippedMapping.insignia_of_ravenholdt = { 137049, }
Engine.Generated.EquippedMapping.kazzalax_fujiedas_fury = { 137053, }
Engine.Generated.EquippedMapping.lady_vashjs_grasp = { 132411, }
Engine.Generated.EquippedMapping.luffa_wrappings = { 137056, }
Engine.Generated.EquippedMapping.majordomos_dinner_bell = { 142168, }
Engine.Generated.EquippedMapping.mangazas_madness = { 132864, }
Engine.Generated.EquippedMapping.mantle_of_the_first_kirin_tor = { 151808, }
Engine.Generated.EquippedMapping.mantle_of_the_master_assassin = { 144236, }
Engine.Generated.EquippedMapping.parsels_tongue = { 151805, }
Engine.Generated.EquippedMapping.sephuzs_secret = { 132452, }
Engine.Generated.EquippedMapping.shadow_satyrs_walk = { 137032, }
Engine.Generated.EquippedMapping.shard_of_the_exodar = { 132410, }
Engine.Generated.EquippedMapping.shivarran_symmetry = { 141321, }
Engine.Generated.EquippedMapping.smoldering_heart = { 116799, 151819, }
Engine.Generated.EquippedMapping.the_deceivers_blood_pact = { 137035, }
Engine.Generated.EquippedMapping.the_emerald_dreamcatcher = { 137062, }
Engine.Generated.EquippedMapping.the_emperors_capacitor = { 144239, }
Engine.Generated.EquippedMapping.the_great_storms_eye = { 151823, }
Engine.Generated.EquippedMapping.the_wildshapers_clutch = { 137094, }
Engine.Generated.EquippedMapping.thraxis_tricksy_treads = { 137031, }
Engine.Generated.EquippedMapping.umbral_moonglaives = { 147012, }
