if GetBuildInfo and (select(4, GetBuildInfo()) < 80000 or select(4, GetBuildInfo()) >= 90000) then return end

if select(3, UnitClass('player')) ~= 10 then return end

local TJ = LibStub('AceAddon-3.0'):GetAddon('ThousandJabs')

TJ:RegisterActionProfileList('custom::monk::brewmaster', 'Thousand Jabs Custom Monk Profile: Brewmaster', 10, 1, [[
actions=auto_attack
actions+=/spear_hand_strike
actions+=/variable,name=heal_threshold,value=health.pct<80
actions+=/purifying_brew,if=stagger.heavy
actions+=/ironskin_brew,if=charges>1&buff.ironskin_brew.down&incoming_damage_1s>0
actions+=/guard,if=talent.guard.enabled&buff.ironskin_brew.down&incoming_damage_1s>(health.max*0.1)
actions+=/chi_wave,if=talent.chi_wave.enabled&variable.heal_threshold
actions+=/call_action_list,name=ooc,if=!in_combat
actions+=/call_action_list,name=oh_shit,if=incoming_damage_5s>=health.max*0.65|health.pct<35
actions+=/call_action_list,name=normal,if!talent.blackout_combo.enabled
actions+=/call_action_list,name=bocombo,if!talent.blackout_combo.enabled
actions.ooc+=/purifying_brew,if=stagger.any
actions.ooc+=/expel_harm,if=variable.heal_threshold
actions.ooc+=/vivify,if=variable.heal_threshold
actions.oh_shit=fortifying_brew
actions.oh_shit+=/ironskin_brew,if=buff.ironskin_brew.down
actions.oh_shit+=/purifying_brew,if=stagger.heavy|stagger.moderate
actions.oh_shit+=/healing_elixir,if=talent.healing_elixir.enabled
actions.oh_shit+=/expel_harm
actions.oh_shit+=/black_ox_brew,if=spell.ironskin_brew.charges=0
actions.normal=keg_smash
actions.normal+=/blackout_strike
actions.normal+=/breath_of_fire,if=debuff.keg_smash.up
actions.normal+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled
actions.normal+=/tiger_palm,if=energy>65
actions.normal+=/tiger_palm,if=buff.eye_of_the_tiger.down|buff.eye_of_the_tiger.remains<gcd*2
actions.normal+=/chi_burst,if=talent.chi_burst.enabled
actions.normal+=/chi_wave,if=talent.chi_wave.enabled
actions.normal+=/expel_harm,if=charges=3&variable.heal_threshold
actions.bocombo=keg_smash
actions.bocombo+=/blackout_strike
actions.bocombo+=/tiger_palm,if=buff.blackout_combo.up
actions.bocombo+=/breath_of_fire,if=debuff.keg_smash.up
actions.bocombo+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled
actions.bocombo+=/tiger_palm,if=energy>65
actions.bocombo+=/tiger_palm,if=buff.eye_of_the_tiger.down|buff.eye_of_the_tiger.remains<gcd*2
actions.bocombo+=/chi_burst,if=talent.chi_burst.enabled
actions.bocombo+=/chi_wave,if=talent.chi_wave.enabled
actions.bocombo+=/expel_harm,if=charges=3&variable.heal_threshold
]])

TJ:RegisterActionProfileList('simc::monk::brewmaster', 'Simulationcraft Monk Profile: Brewmaster', 10, 1, [[
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/potion
actions.precombat+=/chi_burst
actions.precombat+=/chi_wave
actions=auto_attack
actions+=/gift_of_the_ox,if=health<health.max*0.65
actions+=/dampen_harm,if=incoming_damage_1500ms&buff.fortifying_brew.down
actions+=/fortifying_brew,if=incoming_damage_1500ms&(buff.dampen_harm.down|buff.diffuse_magic.down)
actions+=/use_item,name=ashvanes_razor_coral,if=debuff.razor_coral_debuff.down|debuff.conductive_ink_debuff.up&target.health.pct<31|target.time_to_die<20
actions+=/use_items
actions+=/potion
actions+=/blood_fury
actions+=/berserking
actions+=/lights_judgment
actions+=/fireblood
actions+=/ancestral_call
actions+=/bag_of_tricks
actions+=/invoke_niuzao_the_black_ox,if=target.time_to_die>25
actions+=/ironskin_brew,if=buff.blackout_combo.down&incoming_damage_1999ms>(health.max*0.1+stagger.last_tick_damage_4)&buff.elusive_brawler.stack<2&!buff.ironskin_brew.up
actions+=/ironskin_brew,if=cooldown.brews.charges_fractional>1&cooldown.black_ox_brew.remains<3&buff.ironskin_brew.remains<15
actions+=/purifying_brew,if=stagger.pct>(6*(3-(cooldown.brews.charges_fractional)))&(stagger.last_tick_damage_1>((0.02+0.001*(3-cooldown.brews.charges_fractional))*stagger.last_tick_damage_30))
actions+=/black_ox_brew,if=cooldown.brews.charges_fractional<0.5
actions+=/black_ox_brew,if=(energy+(energy.regen*cooldown.keg_smash.remains))<40&buff.blackout_combo.down&cooldown.keg_smash.up
actions+=/keg_smash,if=spell_targets>=2
actions+=/tiger_palm,if=talent.rushing_jade_wind.enabled&buff.blackout_combo.up&buff.rushing_jade_wind.up
actions+=/tiger_palm,if=(talent.invoke_niuzao_the_black_ox.enabled|talent.special_delivery.enabled)&buff.blackout_combo.up
actions+=/expel_harm,if=buff.gift_of_the_ox.stack>4
actions+=/blackout_strike
actions+=/keg_smash
actions+=/concentrated_flame,if=dot.concentrated_flame.remains=0
actions+=/heart_essence,if=!essence.the_crucible_of_flame.major
actions+=/expel_harm,if=buff.gift_of_the_ox.stack>=3
actions+=/rushing_jade_wind,if=buff.rushing_jade_wind.down
actions+=/breath_of_fire,if=buff.blackout_combo.down&(buff.bloodlust.down|(buff.bloodlust.up&&dot.breath_of_fire_dot.refreshable))
actions+=/chi_burst
actions+=/chi_wave
actions+=/expel_harm,if=buff.gift_of_the_ox.stack>=2
actions+=/tiger_palm,if=!talent.blackout_combo.enabled&cooldown.keg_smash.remains>gcd&(energy+(energy.regen*(cooldown.keg_smash.remains+gcd)))>=65
actions+=/arcane_torrent,if=energy<31
actions+=/rushing_jade_wind
]])

TJ:RegisterActionProfileList('simc::monk::windwalker', 'Simulationcraft Monk Profile: Windwalker', 10, 3, [[
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/potion
actions.precombat+=/variable,name=tod_on_use_trinket,op=set,value=equipped.cyclotronic_blast|equipped.lustrous_golden_plumage|equipped.gladiators_badge|equipped.gladiators_medallion|equipped.remote_guidance_device
actions.precombat+=/variable,name=hold_tod,op=set,value=cooldown.touch_of_death.remains+9>target.time_to_die|!talent.serenity.enabled&!variable.tod_on_use_trinket&equipped.dribbling_inkpod&target.time_to_pct_30.remains<130&target.time_to_pct_30.remains>8|target.time_to_die<130&target.time_to_die>cooldown.serenity.remains&cooldown.serenity.remains>2|buff.serenity.up&target.time_to_die>11
actions.precombat+=/variable,name=font_of_power_precombat_channel,op=set,value=19,if=!talent.serenity.enabled&(variable.tod_on_use_trinket|equipped.ashvanes_razor_coral)
actions.precombat+=/use_item,name=azsharas_font_of_power
actions.precombat+=/chi_burst,if=!talent.serenity.enabled|!talent.fist_of_the_white_tiger.enabled
actions.precombat+=/chi_wave,if=talent.fist_of_the_white_tiger.enabled|essence.conflict_and_strife.major
actions.precombat+=/invoke_xuen_the_white_tiger
actions.precombat+=/guardian_of_azeroth
actions=auto_attack
actions+=/spear_hand_strike,if=target.debuff.casting.react
actions+=/touch_of_karma,interval=90,pct_health=0.5
actions+=/potion,if=buff.serenity.up|buff.storm_earth_and_fire.up&dot.touch_of_death.remains|target.time_to_die<=60
actions+=/reverse_harm,if=chi.max-chi>=2&(talent.serenity.enabled|!dot.touch_of_death.remains)&buff.serenity.down&(energy.time_to_max<1|talent.serenity.enabled&cooldown.serenity.remains<2|!talent.serenity.enabled&cooldown.touch_of_death.remains<3&!variable.hold_tod|energy.time_to_max<4&cooldown.fists_of_fury.remains<1.5)
actions+=/fist_of_the_white_tiger,target_if=min:debuff.mark_of_the_crane.remains,if=chi.max-chi>=3&buff.serenity.down&buff.seething_rage.down&(energy.time_to_max<1|talent.serenity.enabled&cooldown.serenity.remains<2|!talent.serenity.enabled&cooldown.touch_of_death.remains<3&!variable.hold_tod|energy.time_to_max<4&cooldown.fists_of_fury.remains<1.5)
actions+=/tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=!combo_break&chi.max-chi>=2&(talent.serenity.enabled|!dot.touch_of_death.remains|active_enemies>2)&buff.seething_rage.down&buff.serenity.down&(energy.time_to_max<1|talent.serenity.enabled&cooldown.serenity.remains<2|!talent.serenity.enabled&cooldown.touch_of_death.remains<3&!variable.hold_tod|energy.time_to_max<4&cooldown.fists_of_fury.remains<1.5)
actions+=/chi_wave,if=!talent.fist_of_the_white_tiger.enabled&prev_gcd.1.tiger_palm&time<=3
actions+=/call_action_list,name=cd_serenity,if=talent.serenity.enabled
actions+=/call_action_list,name=cd_sef,if=!talent.serenity.enabled
actions+=/call_action_list,name=serenity,if=buff.serenity.up
actions+=/call_action_list,name=st,if=active_enemies<3
actions+=/call_action_list,name=aoe,if=active_enemies>=3
actions.aoe=whirling_dragon_punch
actions.aoe+=/energizing_elixir,if=!prev_gcd.1.tiger_palm&chi<=1&energy<50
actions.aoe+=/fists_of_fury,if=energy.time_to_max>1
actions.aoe+=/rising_sun_kick,target_if=min:debuff.mark_of_the_crane.remains,if=(talent.whirling_dragon_punch.enabled&cooldown.rising_sun_kick.duration>cooldown.whirling_dragon_punch.remains+4)&(cooldown.fists_of_fury.remains>3|chi>=5)
actions.aoe+=/rushing_jade_wind,if=buff.rushing_jade_wind.down
actions.aoe+=/spinning_crane_kick,if=combo_strike&(((chi>3|cooldown.fists_of_fury.remains>6)&(chi>=5|cooldown.fists_of_fury.remains>2))|energy.time_to_max<=3|buff.dance_of_chiji.react)
actions.aoe+=/reverse_harm,if=chi.max-chi>=2
actions.aoe+=/chi_burst,if=chi.max-chi>=3
actions.aoe+=/fist_of_the_white_tiger,target_if=min:debuff.mark_of_the_crane.remains,if=chi.max-chi>=3
actions.aoe+=/tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=chi.max-chi>=2&(!talent.hit_combo.enabled|!combo_break)
actions.aoe+=/chi_wave,if=!combo_break
actions.aoe+=/flying_serpent_kick,if=buff.bok_proc.down,interrupt=1
actions.aoe+=/blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike&(buff.bok_proc.up|(talent.hit_combo.enabled&prev_gcd.1.tiger_palm&chi<4))
actions.cd_sef=invoke_xuen_the_white_tiger,if=buff.serenity.down|target.time_to_die<25
actions.cd_sef+=/guardian_of_azeroth,if=target.time_to_die>185|!variable.hold_tod&cooldown.touch_of_death.remains<=14|target.time_to_die<35
actions.cd_sef+=/worldvein_resonance,if=cooldown.touch_of_death.remains>58|cooldown.touch_of_death.remains<2|variable.hold_tod|target.time_to_die<20
actions.cd_sef+=/arcane_torrent,if=chi.max-chi>=1&energy.time_to_max>=0.5
actions.cd_sef+=/touch_of_death,if=!variable.hold_tod&(!equipped.cyclotronic_blast|cooldown.cyclotronic_blast.remains<=1)&(chi>1|energy<40)
actions.cd_sef+=/storm_earth_and_fire,,if=cooldown.storm_earth_and_fire.charges=2|dot.touch_of_death.remains|target.time_to_die<20|(buff.worldvein_resonance.remains>10|cooldown.worldvein_resonance.remains>cooldown.storm_earth_and_fire.full_recharge_time|!essence.worldvein_resonance.major)&(cooldown.touch_of_death.remains>cooldown.storm_earth_and_fire.full_recharge_time|variable.hold_tod&!equipped.dribbling_inkpod)&cooldown.fists_of_fury.remains<=9&chi>=3&cooldown.whirling_dragon_punch.remains<=13
actions.cd_sef+=/blood_of_the_enemy,if=cooldown.touch_of_death.remains>45|variable.hold_tod&cooldown.fists_of_fury.remains<2|target.time_to_die<12|target.time_to_die>100&target.time_to_die<110&(cooldown.fists_of_fury.remains<3|cooldown.whirling_dragon_punch.remains<5|cooldown.rising_sun_kick.remains<5)
actions.cd_sef+=/concentrated_flame,if=!dot.concentrated_flame_burn.remains&((cooldown.concentrated_flame.remains<=cooldown.touch_of_death.remains+1|variable.hold_tod)&(!talent.whirling_dragon_punch.enabled|cooldown.whirling_dragon_punch.remains)&cooldown.rising_sun_kick.remains&cooldown.fists_of_fury.remains&buff.storm_earth_and_fire.down|dot.touch_of_death.remains)|target.time_to_die<8
actions.cd_sef+=/blood_fury,if=cooldown.touch_of_death.remains>30|variable.hold_tod|target.time_to_die<20
actions.cd_sef+=/berserking,if=cooldown.touch_of_death.remains>30|variable.hold_tod|target.time_to_die<15
actions.cd_sef+=/lights_judgment
actions.cd_sef+=/fireblood,if=cooldown.touch_of_death.remains>30|variable.hold_tod|target.time_to_die<10
actions.cd_sef+=/ancestral_call,if=cooldown.touch_of_death.remains>30|variable.hold_tod|target.time_to_die<20
actions.cd_sef+=/bag_of_tricks
actions.cd_sef+=/the_unbound_force
actions.cd_sef+=/purifying_blast
actions.cd_sef+=/reaping_flames
actions.cd_sef+=/focused_azerite_beam
actions.cd_sef+=/memory_of_lucid_dreams,if=energy<40
actions.cd_sef+=/ripple_in_space
actions.cd_sef+=/bag_of_tricks
actions.cd_serenity=invoke_xuen_the_white_tiger,if=buff.serenity.down|target.time_to_die<25
actions.cd_serenity+=/guardian_of_azeroth,if=buff.serenity.down&(target.time_to_die>185|cooldown.serenity.remains<=7)|target.time_to_die<35
actions.cd_serenity+=/blood_fury,if=cooldown.serenity.remains>20|target.time_to_die<20
actions.cd_serenity+=/berserking,if=cooldown.serenity.remains>20|target.time_to_die<15
actions.cd_serenity+=/arcane_torrent,if=buff.serenity.down&chi.max-chi>=1&energy.time_to_max>=0.5
actions.cd_serenity+=/lights_judgment
actions.cd_serenity+=/fireblood,if=cooldown.serenity.remains>20|target.time_to_die<10
actions.cd_serenity+=/ancestral_call,if=cooldown.serenity.remains>20|target.time_to_die<20
actions.cd_serenity+=/bag_of_tricks
actions.cd_serenity+=/touch_of_death,if=!variable.hold_tod
actions.cd_serenity+=/blood_of_the_enemy,if=buff.serenity.down&(cooldown.serenity.remains>20|cooldown.serenity.remains<2)|target.time_to_die<15
actions.cd_serenity+=/worldvein_resonance,if=buff.serenity.down&(cooldown.serenity.remains>15|cooldown.serenity.remains<2)|target.time_to_die<20
actions.cd_serenity+=/concentrated_flame,if=buff.serenity.down&(cooldown.serenity.remains|cooldown.concentrated_flame.charges=2)&!dot.concentrated_flame_burn.remains&(cooldown.rising_sun_kick.remains&cooldown.fists_of_fury.remains|target.time_to_die<8)
actions.cd_serenity+=/serenity
actions.cd_serenity+=/the_unbound_force,if=buff.serenity.down
actions.cd_serenity+=/purifying_blast,if=buff.serenity.down
actions.cd_serenity+=/reaping_flames,if=buff.serenity.down
actions.cd_serenity+=/focused_azerite_beam,if=buff.serenity.down
actions.cd_serenity+=/memory_of_lucid_dreams,if=buff.serenity.down&energy<40
actions.cd_serenity+=/ripple_in_space,if=buff.serenity.down
actions.cd_serenity+=/bag_of_tricks,if=buff.serenity.down
actions.serenity=fists_of_fury,if=buff.serenity.remains<1|active_enemies>1
actions.serenity+=/spinning_crane_kick,if=combo_strike&(active_enemies>2|active_enemies>1&!cooldown.rising_sun_kick.up)
actions.serenity+=/rising_sun_kick,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike
actions.serenity+=/fists_of_fury,interrupt_if=gcd.remains=0
actions.serenity+=/fist_of_the_white_tiger,target_if=min:debuff.mark_of_the_crane.remains,if=chi<3
actions.serenity+=/reverse_harm,if=chi.max-chi>1&energy.time_to_max<1
actions.serenity+=/blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike|!talent.hit_combo.enabled
actions.serenity+=/spinning_crane_kick
actions.st=whirling_dragon_punch
actions.st+=/fists_of_fury,if=talent.serenity.enabled|cooldown.touch_of_death.remains>6|variable.hold_tod
actions.st+=/rising_sun_kick,target_if=min:debuff.mark_of_the_crane.remains,if=cooldown.touch_of_death.remains>2|variable.hold_tod
actions.st+=/rushing_jade_wind,if=buff.rushing_jade_wind.down&active_enemies>1
actions.st+=/reverse_harm,if=chi.max-chi>1
actions.st+=/fist_of_the_white_tiger,target_if=min:debuff.mark_of_the_crane.remains,if=chi<3
actions.st+=/energizing_elixir,if=chi<=3&energy<50
actions.st+=/chi_burst,if=chi.max-chi>0&active_enemies=1|chi.max-chi>1
actions.st+=/tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike&chi.max-chi>3&!dot.touch_of_death.remains&buff.storm_earth_and_fire.down
actions.st+=/chi_wave
actions.st+=/spinning_crane_kick,if=combo_strike&buff.dance_of_chiji.react
actions.st+=/blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike&((cooldown.touch_of_death.remains>2|variable.hold_tod)&(cooldown.rising_sun_kick.remains>2&cooldown.fists_of_fury.remains>2|cooldown.rising_sun_kick.remains<3&cooldown.fists_of_fury.remains>3&chi>2|cooldown.rising_sun_kick.remains>3&cooldown.fists_of_fury.remains<3&chi>4|chi>5)|buff.bok_proc.up)
actions.st+=/tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike&chi.max-chi>1
actions.st+=/flying_serpent_kick,interrupt=1
actions.st+=/blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=(cooldown.fists_of_fury.remains<3&chi=2|energy.time_to_max<1)&(prev_gcd.1.tiger_palm|chi.max-chi<2)
]])

