local _, internal = ...
internal.apls = internal.apls or {}

internal.apls["legion-dev::Tier19P::Rogue_Assassination_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/apply_poison
actions.precombat+=/stealth
actions.precombat+=/potion,name=draenic_agility
actions.precombat+=/marked_for_death
actions=potion,name=draenic_agility,if=buff.bloodlust.react|target.time_to_die<=25|debuff.vendetta.up
actions+=/blood_fury,if=debuff.vendetta.up
actions+=/berserking,if=debuff.vendetta.up
actions+=/arcane_torrent,if=debuff.vendetta.up&energy.deficit>50
actions+=/call_action_list,name=cds
actions+=/rupture,if=combo_points>=2&!ticking&time<10&!artifact.urge_to_kill.enabled
actions+=/rupture,if=combo_points>=4&!ticking
actions+=/pool_resource,for_next=1
actions+=/kingsbane,if=(buff.vendetta.up|cooldown.vendetta.remains>30)&dot.rupture.exsanguinated
actions+=/run_action_list,name=exsang_combo,if=cooldown.exsanguinate.remains<3&talent.exsanguinate.enabled
actions+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=7
actions+=/call_action_list,name=exsang,if=dot.rupture.exsanguinated&spell_targets.fan_of_knives<=2
actions+=/rupture,if=talent.exsanguinate.enabled&remains-cooldown.exsanguinate.remains<(4+cp_max_spend*4)*0.3&new_duration-cooldown.exsanguinate.remains>=(4+cp_max_spend*4)*0.3+3
actions+=/call_action_list,name=finish
actions+=/call_action_list,name=build
actions.cds=marked_for_death,cycle_targets=1,target_if=min:target.time_to_die,if=combo_points.deficit>=5
actions.cds+=/vendetta,if=target.time_to_die<20|artifact.urge_to_kill.enabled&dot.rupture.ticking&cooldown.exsanguinate.remains<5&(energy<55|time<10|spell_targets.fan_of_knives>=3)|!artifact.urge_to_kill.enabled&dot.rupture.ticking&cooldown.exsanguinate.remains<1
actions.cds+=/vanish,if=talent.subterfuge.enabled&combo_points<=2&!dot.rupture.exsanguinated|talent.shadow_focus.enabled&!dot.rupture.exsanguinated&combo_points.deficit>=2
actions.exsang_combo=vanish,if=talent.nightstalker.enabled&combo_points>=cp_max_spend&cooldown.exsanguinate.remains<1&gcd.remains=0&energy>=25
actions.exsang_combo+=/rupture,if=combo_points>=cp_max_spend&(!talent.nightstalker.enabled|buff.vanish.up|cooldown.vanish.remains>15)&cooldown.exsanguinate.remains<1
actions.exsang_combo+=/exsanguinate,if=prev_gcd.rupture&dot.rupture.remains>22+4*talent.deeper_stratagem.enabled&cooldown.vanish.remains>10
actions.exsang_combo+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=7
actions.exsang_combo+=/hemorrhage,if=spell_targets.fan_of_knives>=2&!ticking
actions.exsang_combo+=/call_action_list,name=build
actions.garrote=pool_resource,for_next=1
actions.garrote+=/garrote,cycle_targets=1,if=talent.subterfuge.enabled&!ticking&combo_points.deficit>=1&spell_targets.fan_of_knives>=2
actions.garrote+=/pool_resource,for_next=1
actions.garrote+=/garrote,if=combo_points.deficit>=1&!exsanguinated
actions.exsang=rupture,if=combo_points>=cp_max_spend&ticks_remain<2
actions.exsang+=/death_from_above,if=combo_points>=cp_max_spend-1&dot.rupture.remains>3
actions.exsang+=/envenom,if=combo_points>=cp_max_spend-1&dot.rupture.remains>3
actions.finish=rupture,cycle_targets=1,if=!ticking&combo_points>=cp_max_spend-1&spell_targets.fan_of_knives>1&target.time_to_die-remains>6
actions.finish+=/rupture,if=combo_points>=cp_max_spend-1&refreshable&!exsanguinated
actions.finish+=/death_from_above,if=combo_points>=cp_max_spend-1&spell_targets.fan_of_knives<=7
actions.finish+=/envenom,if=combo_points>=cp_max_spend-1&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&energy.deficit<40&spell_targets.fan_of_knives<=6
actions.finish+=/envenom,if=combo_points>=cp_max_spend&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&cooldown.garrote.remains<1&spell_targets.fan_of_knives<=6
actions.build=hemorrhage,cycle_targets=1,if=combo_points.deficit>=1&refreshable&dot.rupture.remains>6&spell_targets.fan_of_knives>1&spell_targets.fan_of_knives<=4
actions.build+=/fan_of_knives,if=spell_targets>=2&(combo_points.deficit>=1|spell_targets>=7)
actions.build+=/hemorrhage,if=(combo_points.deficit>=1&refreshable)|(combo_points.deficit=1&(dot.rupture.exsanguinated&dot.rupture.remains<=2|cooldown.exsanguinate.remains<=2))
actions.build+=/mutilate,if=combo_points.deficit<=1&energy.deficit<=30
actions.build+=/mutilate,if=combo_points.deficit>=2&cooldown.garrote.remains>2
]]

internal.apls["legion-dev::Tier19P::Rogue_Outlaw_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=draenic_agility
actions.precombat+=/marked_for_death
actions=potion,name=draenic_agility,if=buff.bloodlust.react|target.time_to_die<=25|buff.adrenaline_rush.up
actions+=/blade_flurry,if=(spell_targets.blade_flurry>=2&!buff.blade_flurry.up)|(spell_targets.blade_flurry<2&buff.blade_flurry.up)
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent,if=energy.deficit>40
actions+=/adrenaline_rush,if=!buff.adrenaline_rush.up
actions+=/pool_resource,for_next=1
actions+=/ambush
actions+=/pool_resource,for_next=1,extra_amount=60
actions+=/vanish,if=combo_points.deficit>=2&energy>60
actions+=/pool_resource,for_next=1,extra_amount=60
actions+=/shadowmeld,if=combo_points.deficit>=2&energy>60
actions+=/slice_and_dice,if=combo_points>=5&buff.slice_and_dice.remains<target.time_to_die&buff.slice_and_dice.remains<6
actions+=/roll_the_bones,if=combo_points>=5&buff.roll_the_bones.remains<target.time_to_die&(buff.roll_the_bones.remains<3|buff.roll_the_bones.remains<duration*0.3%rtb_buffs|(rtb_buffs<=1|rtb_buffs=2&!buff.shark_infested_waters.up&!buff.jolly_roger.up&!(buff.broadsides.up&buff.true_bearing.up)))
actions+=/killing_spree,if=energy.time_to_max>5|energy<15
actions+=/cannonball_barrage,if=spell_targets.cannonball_barrage>=1
actions+=/curse_of_the_dreadblades,if=combo_points.deficit>=4
actions+=/marked_for_death,cycle_targets=1,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled
actions+=/call_action_list,name=finisher,if=combo_points>=5+talent.deeper_strategem.enabled
actions+=/call_action_list,name=generator,if=combo_points<5+talent.deeper_strategem.enabled
actions.finisher=death_from_above
actions.finisher+=/run_through
actions.generator=ghostly_strike,if=talent.ghostly_strike.enabled&debuff.ghostly_strike.remains<duration*0.3
actions.generator+=/pistol_shot,if=buff.opportunity.up&energy<60
actions.generator+=/saber_slash
]]

internal.apls["legion-dev::Tier19P::Rogue_Subtlety_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=draenic_agility
actions.precombat+=/marked_for_death
actions.precombat+=/symbols_of_death
actions=potion,name=draenic_agility,if=buff.bloodlust.react|target.time_to_die<=25|buff.shadow_blades.up
actions+=/blood_fury,if=buff.shadow_dance.up|buff.vanish.up|buff.stealth.up
actions+=/berserking,if=buff.shadow_dance.up|buff.vanish.up|buff.stealth.up
actions+=/arcane_torrent,if=energy.deficit>70&(buff.shadow_dance.up|buff.vanish.up|buff.stealth.up)
actions+=/shadow_blades,if=!buff.shadow_blades.up&energy.deficit<20&(buff.shadow_dance.up|buff.vanish.up|buff.stealth.up)
actions+=/goremaws_bite,if=(combo_points.max-combo_points>=2&energy.deficit>55&time<10)|(combo_points.max-combo_points>=4&energy.deficit>45)|target.time_to_die<8
actions+=/symbols_of_death,if=buff.symbols_of_death.remains<target.time_to_die-4&buff.symbols_of_death.remains<=10.5&buff.shadowmeld.down
actions+=/shuriken_storm,if=buff.stealth.up&talent.premeditation.enabled&combo_points.max-combo_points>=3&spell_targets.shuriken_storm>=7
actions+=/shuriken_storm,if=buff.stealth.up&!buff.death.up&combo_points.max-combo_points>=2&((!talent.premeditation.enabled&spell_targets.shuriken_storm>=4)|spell_targets.shuriken_storm>=8)
actions+=/shadowstrike,if=combo_points.max-combo_points>=2
actions+=/pool_resource,for_next=1,extra_amount=energy.max-talent.master_of_shadows.enabled*30
actions+=/vanish,if=(energy.deficit<talent.master_of_shadows.enabled*30&combo_points.max-combo_points>=3&cooldown.shadow_dance.charges<2)|target.time_to_die<8
actions+=/pool_resource,for_next=1,extra_amount=energy.max-talent.master_of_shadows.enabled*30
actions+=/shadow_dance,if=combo_points.max-combo_points>=2&((cooldown.vanish.remains&buff.symbols_of_death.remains<=10.5&energy.deficit<talent.master_of_shadows.enabled*30)|cooldown.shadow_dance.charges>=2|target.time_to_die<25)
actions+=/shadowmeld,if=energy>40&combo_points.max-combo_points>=3&!(buff.shadow_dance.up|buff.vanish.up|buff.stealth.up)
actions+=/enveloping_shadows,if=buff.enveloping_shadows.remains<target.time_to_die&((buff.enveloping_shadows.remains<=10.8+talent.deeper_strategem.enabled*1.8&combo_points>=5+talent.deeper_strategem.enabled)|buff.enveloping_shadows.remains<=6)
actions+=/marked_for_death,cycle_targets=1,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled
actions+=/run_action_list,name=finisher,if=combo_points>=5
actions+=/run_action_list,name=generator,if=combo_points<5
actions.finisher=death_from_above,if=spell_targets.death_from_above>=10
actions.finisher+=/nightblade,if=!dot.nightblade.ticking|dot.nightblade.remains<duration*0.3
actions.finisher+=/nightblade,cycle_targets=1,target_if=max:target.time_to_die,if=active_dot.nightblade<6&target.time_to_die>6&(!dot.nightblade.ticking|dot.nightblade.remains<duration*0.3)
actions.finisher+=/death_from_above
actions.finisher+=/eviscerate
actions.generator=shuriken_storm,if=spell_targets.shuriken_storm>=2
actions.generator+=/gloomblade,if=energy.time_to_max<2.5
actions.generator+=/backstab,if=energy.time_to_max<2.5
]]

internal.apls["legion-dev::Tier19H::Rogue_Assassination_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/apply_poison
actions.precombat+=/stealth
actions.precombat+=/potion,name=draenic_agility
actions.precombat+=/marked_for_death
actions=potion,name=draenic_agility,if=buff.bloodlust.react|target.time_to_die<=25|debuff.vendetta.up
actions+=/blood_fury,if=debuff.vendetta.up
actions+=/berserking,if=debuff.vendetta.up
actions+=/arcane_torrent,if=debuff.vendetta.up&energy.deficit>50
actions+=/call_action_list,name=cds
actions+=/rupture,if=combo_points>=2&!ticking&time<10&!artifact.urge_to_kill.enabled
actions+=/rupture,if=combo_points>=4&!ticking
actions+=/pool_resource,for_next=1
actions+=/kingsbane,if=(buff.vendetta.up|cooldown.vendetta.remains>30)&dot.rupture.exsanguinated
actions+=/run_action_list,name=exsang_combo,if=cooldown.exsanguinate.remains<3&talent.exsanguinate.enabled
actions+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=7
actions+=/call_action_list,name=exsang,if=dot.rupture.exsanguinated&spell_targets.fan_of_knives<=2
actions+=/rupture,if=talent.exsanguinate.enabled&remains-cooldown.exsanguinate.remains<(4+cp_max_spend*4)*0.3&new_duration-cooldown.exsanguinate.remains>=(4+cp_max_spend*4)*0.3+3
actions+=/call_action_list,name=finish
actions+=/call_action_list,name=build
actions.cds=marked_for_death,cycle_targets=1,target_if=min:target.time_to_die,if=combo_points.deficit>=5
actions.cds+=/vendetta,if=target.time_to_die<20|artifact.urge_to_kill.enabled&dot.rupture.ticking&cooldown.exsanguinate.remains<5&(energy<55|time<10|spell_targets.fan_of_knives>=3)|!artifact.urge_to_kill.enabled&dot.rupture.ticking&cooldown.exsanguinate.remains<1
actions.cds+=/vanish,if=talent.subterfuge.enabled&combo_points<=2&!dot.rupture.exsanguinated|talent.shadow_focus.enabled&!dot.rupture.exsanguinated&combo_points.deficit>=2
actions.exsang_combo=vanish,if=talent.nightstalker.enabled&combo_points>=cp_max_spend&cooldown.exsanguinate.remains<1&gcd.remains=0&energy>=25
actions.exsang_combo+=/rupture,if=combo_points>=cp_max_spend&(!talent.nightstalker.enabled|buff.vanish.up|cooldown.vanish.remains>15)&cooldown.exsanguinate.remains<1
actions.exsang_combo+=/exsanguinate,if=prev_gcd.rupture&dot.rupture.remains>22+4*talent.deeper_stratagem.enabled&cooldown.vanish.remains>10
actions.exsang_combo+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=7
actions.exsang_combo+=/hemorrhage,if=spell_targets.fan_of_knives>=2&!ticking
actions.exsang_combo+=/call_action_list,name=build
actions.garrote=pool_resource,for_next=1
actions.garrote+=/garrote,cycle_targets=1,if=talent.subterfuge.enabled&!ticking&combo_points.deficit>=1&spell_targets.fan_of_knives>=2
actions.garrote+=/pool_resource,for_next=1
actions.garrote+=/garrote,if=combo_points.deficit>=1&!exsanguinated
actions.exsang=rupture,if=combo_points>=cp_max_spend&ticks_remain<2
actions.exsang+=/death_from_above,if=combo_points>=cp_max_spend-1&dot.rupture.remains>3
actions.exsang+=/envenom,if=combo_points>=cp_max_spend-1&dot.rupture.remains>3
actions.finish=rupture,cycle_targets=1,if=!ticking&combo_points>=cp_max_spend-1&spell_targets.fan_of_knives>1&target.time_to_die-remains>6
actions.finish+=/rupture,if=combo_points>=cp_max_spend-1&refreshable&!exsanguinated
actions.finish+=/death_from_above,if=combo_points>=cp_max_spend-1&spell_targets.fan_of_knives<=7
actions.finish+=/envenom,if=combo_points>=cp_max_spend-1&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&energy.deficit<40&spell_targets.fan_of_knives<=6
actions.finish+=/envenom,if=combo_points>=cp_max_spend&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&cooldown.garrote.remains<1&spell_targets.fan_of_knives<=6
actions.build=hemorrhage,cycle_targets=1,if=combo_points.deficit>=1&refreshable&dot.rupture.remains>6&spell_targets.fan_of_knives>1&spell_targets.fan_of_knives<=4
actions.build+=/fan_of_knives,if=spell_targets>=2&(combo_points.deficit>=1|spell_targets>=7)
actions.build+=/hemorrhage,if=(combo_points.deficit>=1&refreshable)|(combo_points.deficit=1&(dot.rupture.exsanguinated&dot.rupture.remains<=2|cooldown.exsanguinate.remains<=2))
actions.build+=/mutilate,if=combo_points.deficit<=1&energy.deficit<=30
actions.build+=/mutilate,if=combo_points.deficit>=2&cooldown.garrote.remains>2
]]

internal.apls["legion-dev::Tier19H::Rogue_Outlaw_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=draenic_agility
actions.precombat+=/marked_for_death
actions=potion,name=draenic_agility,if=buff.bloodlust.react|target.time_to_die<=25|buff.adrenaline_rush.up
actions+=/blade_flurry,if=(spell_targets.blade_flurry>=2&!buff.blade_flurry.up)|(spell_targets.blade_flurry<2&buff.blade_flurry.up)
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent,if=energy.deficit>40
actions+=/adrenaline_rush,if=!buff.adrenaline_rush.up
actions+=/pool_resource,for_next=1
actions+=/ambush
actions+=/pool_resource,for_next=1,extra_amount=60
actions+=/vanish,if=combo_points.deficit>=2&energy>60
actions+=/pool_resource,for_next=1,extra_amount=60
actions+=/shadowmeld,if=combo_points.deficit>=2&energy>60
actions+=/slice_and_dice,if=combo_points>=5&buff.slice_and_dice.remains<target.time_to_die&buff.slice_and_dice.remains<6
actions+=/roll_the_bones,if=combo_points>=5&buff.roll_the_bones.remains<target.time_to_die&(buff.roll_the_bones.remains<3|buff.roll_the_bones.remains<duration*0.3%rtb_buffs|(rtb_buffs<=1|rtb_buffs=2&!buff.shark_infested_waters.up&!buff.jolly_roger.up&!(buff.broadsides.up&buff.true_bearing.up)))
actions+=/killing_spree,if=energy.time_to_max>5|energy<15
actions+=/cannonball_barrage,if=spell_targets.cannonball_barrage>=1
actions+=/curse_of_the_dreadblades,if=combo_points.deficit>=4
actions+=/marked_for_death,cycle_targets=1,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled
actions+=/call_action_list,name=finisher,if=combo_points>=5+talent.deeper_strategem.enabled
actions+=/call_action_list,name=generator,if=combo_points<5+talent.deeper_strategem.enabled
actions.finisher=death_from_above
actions.finisher+=/run_through
actions.generator=ghostly_strike,if=talent.ghostly_strike.enabled&debuff.ghostly_strike.remains<duration*0.3
actions.generator+=/pistol_shot,if=buff.opportunity.up&energy<60
actions.generator+=/saber_slash
]]

internal.apls["legion-dev::Tier19H::Rogue_Subtlety_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=draenic_agility
actions.precombat+=/marked_for_death
actions.precombat+=/symbols_of_death
actions=potion,name=draenic_agility,if=buff.bloodlust.react|target.time_to_die<=25|buff.shadow_blades.up
actions+=/blood_fury,if=buff.shadow_dance.up|buff.vanish.up|buff.stealth.up
actions+=/berserking,if=buff.shadow_dance.up|buff.vanish.up|buff.stealth.up
actions+=/arcane_torrent,if=energy.deficit>70&(buff.shadow_dance.up|buff.vanish.up|buff.stealth.up)
actions+=/shadow_blades,if=!buff.shadow_blades.up&energy.deficit<20&(buff.shadow_dance.up|buff.vanish.up|buff.stealth.up)
actions+=/goremaws_bite,if=(combo_points.max-combo_points>=2&energy.deficit>55&time<10)|(combo_points.max-combo_points>=4&energy.deficit>45)|target.time_to_die<8
actions+=/symbols_of_death,if=buff.symbols_of_death.remains<target.time_to_die-4&buff.symbols_of_death.remains<=10.5&buff.shadowmeld.down
actions+=/shuriken_storm,if=buff.stealth.up&talent.premeditation.enabled&combo_points.max-combo_points>=3&spell_targets.shuriken_storm>=7
actions+=/shuriken_storm,if=buff.stealth.up&!buff.death.up&combo_points.max-combo_points>=2&((!talent.premeditation.enabled&spell_targets.shuriken_storm>=4)|spell_targets.shuriken_storm>=8)
actions+=/shadowstrike,if=combo_points.max-combo_points>=2
actions+=/pool_resource,for_next=1,extra_amount=energy.max-talent.master_of_shadows.enabled*30
actions+=/vanish,if=(energy.deficit<talent.master_of_shadows.enabled*30&combo_points.max-combo_points>=3&cooldown.shadow_dance.charges<2)|target.time_to_die<8
actions+=/pool_resource,for_next=1,extra_amount=energy.max-talent.master_of_shadows.enabled*30
actions+=/shadow_dance,if=combo_points.max-combo_points>=2&((cooldown.vanish.remains&buff.symbols_of_death.remains<=10.5&energy.deficit<talent.master_of_shadows.enabled*30)|cooldown.shadow_dance.charges>=2|target.time_to_die<25)
actions+=/shadowmeld,if=energy>40&combo_points.max-combo_points>=3&!(buff.shadow_dance.up|buff.vanish.up|buff.stealth.up)
actions+=/enveloping_shadows,if=buff.enveloping_shadows.remains<target.time_to_die&((buff.enveloping_shadows.remains<=10.8+talent.deeper_strategem.enabled*1.8&combo_points>=5+talent.deeper_strategem.enabled)|buff.enveloping_shadows.remains<=6)
actions+=/marked_for_death,cycle_targets=1,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled
actions+=/run_action_list,name=finisher,if=combo_points>=5
actions+=/run_action_list,name=generator,if=combo_points<5
actions.finisher=death_from_above,if=spell_targets.death_from_above>=10
actions.finisher+=/nightblade,if=!dot.nightblade.ticking|dot.nightblade.remains<duration*0.3
actions.finisher+=/nightblade,cycle_targets=1,target_if=max:target.time_to_die,if=active_dot.nightblade<6&target.time_to_die>6&(!dot.nightblade.ticking|dot.nightblade.remains<duration*0.3)
actions.finisher+=/death_from_above
actions.finisher+=/eviscerate
actions.generator=shuriken_storm,if=spell_targets.shuriken_storm>=2
actions.generator+=/gloomblade,if=energy.time_to_max<2.5
actions.generator+=/backstab,if=energy.time_to_max<2.5
]]

