local TJ = LibStub('AceAddon-3.0'):GetAddon('ThousandJabs')
local Core = TJ:GetModule('Core')
TJ.Generated = TJ.Generated or {}
TJ.Generated.EquippedMapping = TJ.Generated.EquippedMapping or {}

TJ.Generated.EquippedMapping.ailuro_pouncers = { 137024, }
TJ.Generated.EquippedMapping.archavons_heavy_hand = { 137060, }
TJ.Generated.EquippedMapping.convergence_of_fates = { 140806, }
TJ.Generated.EquippedMapping.denial_of_the_halfgiants = { 137100, }
TJ.Generated.EquippedMapping.draught_of_souls = { 140808, }
TJ.Generated.EquippedMapping.drinking_horn_cover = { 137097, }
TJ.Generated.EquippedMapping.frizzos_fingertrap = { 137043, }
TJ.Generated.EquippedMapping.gnawed_thumb_ring = { 134526, }
TJ.Generated.EquippedMapping.greenskins_waterlogged_wristcuffs = { 137099, }
TJ.Generated.EquippedMapping.hidden_masters_forbidden_touch = { 137057, }
TJ.Generated.EquippedMapping.shadow_satyrs_walk = { 137032, }
TJ.Generated.EquippedMapping.shivarran_symmetry = { 141321, }
TJ.Generated.EquippedMapping.the_emerald_dreamcatcher = { 137062, }
TJ.Generated.EquippedMapping.the_emperors_capacitor = { 144239, }
TJ.Generated.EquippedMapping.thraxis_tricksy_treads = { 137031, }
TJ.Generated.EquippedMapping.weight_of_the_earth = { 137077, }
