local TJ = LibStub('AceAddon-3.0'):GetAddon('ThousandJabs')
local Core = TJ:GetModule('Core')
TJ.Generated = TJ.Generated or {}
TJ.Generated.EquippedMapping = TJ.Generated.EquippedMapping or {}

TJ.Generated.EquippedMapping.ailuro_pouncers = { 137024, }
TJ.Generated.EquippedMapping.call_of_the_wild = { 137101, }
TJ.Generated.EquippedMapping.chatoyant_signet = { 137040, }
TJ.Generated.EquippedMapping.cold_heart = { 151796, }
TJ.Generated.EquippedMapping.consorts_cold_core = { 144293, }
TJ.Generated.EquippedMapping.convergence_of_fates = { 140806, }
TJ.Generated.EquippedMapping.denial_of_the_halfgiants = { 137100, }
TJ.Generated.EquippedMapping.draught_of_souls = { 140808, }
TJ.Generated.EquippedMapping.drinking_horn_cover = { 137097, }
TJ.Generated.EquippedMapping.duskwalkers_footpads = { 137030, }
TJ.Generated.EquippedMapping.frizzos_fingertrap = { 137043, }
TJ.Generated.EquippedMapping.gnawed_thumb_ring = { 134526, }
TJ.Generated.EquippedMapping.greenskins_waterlogged_wristcuffs = { 137099, }
TJ.Generated.EquippedMapping.hidden_masters_forbidden_touch = { 137057, }
TJ.Generated.EquippedMapping.insignia_of_ravenholdt = { 137049, }
TJ.Generated.EquippedMapping.katsuos_eclipse = { 137029, }
TJ.Generated.EquippedMapping.kazzalax_fujiedas_fury = { 137053, }
TJ.Generated.EquippedMapping.koltiras_newfound_will = { 132366, }
TJ.Generated.EquippedMapping.lady_and_the_child = { 144295, }
TJ.Generated.EquippedMapping.lady_vashjs_grasp = { 132411, }
TJ.Generated.EquippedMapping.luffa_wrappings = { 137056, }
TJ.Generated.EquippedMapping.mangazas_madness = { 132864, }
TJ.Generated.EquippedMapping.mantle_of_the_first_kirin_tor = { 151808, }
TJ.Generated.EquippedMapping.mantle_of_the_master_assassin = { 144236, }
TJ.Generated.EquippedMapping.mystic_kilt_of_the_rune_master = { 132451, }
TJ.Generated.EquippedMapping.parsels_tongue = { 151805, }
TJ.Generated.EquippedMapping.perseverance_of_the_ebon_martyr = { 132459, }
TJ.Generated.EquippedMapping.qapla_eredun_war_order = { 137227, }
TJ.Generated.EquippedMapping.sephuzs_secret = { 132452, }
TJ.Generated.EquippedMapping.shadow_satyrs_walk = { 137032, }
TJ.Generated.EquippedMapping.shard_of_the_exodar = { 132410, }
TJ.Generated.EquippedMapping.shivarran_symmetry = { 141321, }
TJ.Generated.EquippedMapping.smoldering_heart = { 116799, 151819, }
TJ.Generated.EquippedMapping.the_deceivers_blood_pact = { 137035, }
TJ.Generated.EquippedMapping.the_emerald_dreamcatcher = { 137062, }
TJ.Generated.EquippedMapping.the_emperors_capacitor = { 144239, }
TJ.Generated.EquippedMapping.the_first_of_the_dead = { 151818, }
TJ.Generated.EquippedMapping.the_great_storms_eye = { 151823, }
TJ.Generated.EquippedMapping.the_wildshapers_clutch = { 137094, }
TJ.Generated.EquippedMapping.thraxis_tricksy_treads = { 137031, }
TJ.Generated.EquippedMapping.umbral_moonglaives = { 147012, }
