if GetBuildInfo and (select(4, GetBuildInfo()) < 80000 or select(4, GetBuildInfo()) >= 90000) then return end

if select(3, UnitClass('player')) ~= 1 then return end

local TJ = LibStub('AceAddon-3.0'):GetAddon('ThousandJabs')

TJ:RegisterActionProfileList('simc::warrior::arms', 'Simulationcraft Warrior Profile: Arms', 1, 1, [[
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/use_item,name=azsharas_font_of_power
actions.precombat+=/worldvein_resonance
actions.precombat+=/memory_of_lucid_dreams
actions.precombat+=/guardian_of_azeroth
actions.precombat+=/potion
actions=charge
actions+=/auto_attack
actions+=/potion,if=target.health.pct<21&buff.memory_of_lucid_dreams.up|!essence.memory_of_lucid_dreams.major
actions+=/blood_fury,if=buff.memory_of_lucid_dreams.remains<5|(!essence.memory_of_lucid_dreams.major&debuff.colossus_smash.up)
actions+=/berserking,if=buff.memory_of_lucid_dreams.up|(!essence.memory_of_lucid_dreams.major&debuff.colossus_smash.up)
actions+=/arcane_torrent,if=cooldown.mortal_strike.remains>1.5&buff.memory_of_lucid_dreams.down&rage<50
actions+=/lights_judgment,if=debuff.colossus_smash.down&buff.memory_of_lucid_dreams.down&cooldown.mortal_strike.remains
actions+=/fireblood,if=buff.memory_of_lucid_dreams.remains<5|(!essence.memory_of_lucid_dreams.major&debuff.colossus_smash.up)
actions+=/ancestral_call,if=buff.memory_of_lucid_dreams.remains<5|(!essence.memory_of_lucid_dreams.major&debuff.colossus_smash.up)
actions+=/bag_of_tricks,if=debuff.colossus_smash.down&buff.memory_of_lucid_dreams.down&cooldown.mortal_strike.remains
actions+=/avatar,if=cooldown.colossus_smash.remains<8|(talent.warbreaker.enabled&cooldown.warbreaker.remains<8)
actions+=/sweeping_strikes,if=spell_targets.whirlwind>1&(cooldown.bladestorm.remains>10|cooldown.colossus_smash.remains>8|azerite.test_of_might.enabled)
actions+=/blood_of_the_enemy,if=buff.test_of_might.up|(debuff.colossus_smash.up&!azerite.test_of_might.enabled)
actions+=/purifying_blast,if=!debuff.colossus_smash.up&!buff.test_of_might.up
actions+=/ripple_in_space,if=!debuff.colossus_smash.up&!buff.test_of_might.up
actions+=/worldvein_resonance,if=!debuff.colossus_smash.up&!buff.test_of_might.up
actions+=/focused_azerite_beam,if=!debuff.colossus_smash.up&!buff.test_of_might.up
actions+=/reaping_flames,if=!debuff.colossus_smash.up&!buff.test_of_might.up
actions+=/concentrated_flame,if=!debuff.colossus_smash.up&!buff.test_of_might.up&dot.concentrated_flame_burn.remains=0
actions+=/the_unbound_force,if=buff.reckless_force.up
actions+=/guardian_of_azeroth,if=cooldown.colossus_smash.remains<10
actions+=/memory_of_lucid_dreams,if=!talent.warbreaker.enabled&cooldown.colossus_smash.remains<gcd&(target.time_to_die>150|target.health.pct<20)
actions+=/memory_of_lucid_dreams,if=talent.warbreaker.enabled&cooldown.warbreaker.remains<gcd&(target.time_to_die>150|target.health.pct<20)
actions+=/run_action_list,name=hac,if=raid_event.adds.exists
actions+=/run_action_list,name=five_target,if=spell_targets.whirlwind>4
actions+=/run_action_list,name=execute,if=(talent.massacre.enabled&target.health.pct<35)|target.health.pct<20
actions+=/run_action_list,name=single_target
actions.execute=skullsplitter,if=rage<60&buff.deadly_calm.down&buff.memory_of_lucid_dreams.down
actions.execute+=/ravager,if=!buff.deadly_calm.up&(cooldown.colossus_smash.remains<2|(talent.warbreaker.enabled&cooldown.warbreaker.remains<2))
actions.execute+=/colossus_smash,if=!essence.memory_of_lucid_dreams.major|(buff.memory_of_lucid_dreams.up|cooldown.memory_of_lucid_dreams.remains>10)
actions.execute+=/warbreaker,if=!essence.memory_of_lucid_dreams.major|(buff.memory_of_lucid_dreams.up|cooldown.memory_of_lucid_dreams.remains>10)
actions.execute+=/deadly_calm
actions.execute+=/bladestorm,if=!buff.memory_of_lucid_dreams.up&buff.test_of_might.up&rage<30&!buff.deadly_calm.up
actions.execute+=/cleave,if=spell_targets.whirlwind>2
actions.execute+=/slam,if=buff.crushing_assault.up&buff.memory_of_lucid_dreams.down
actions.execute+=/mortal_strike,if=buff.overpower.stack=2&talent.dreadnaught.enabled|buff.executioners_precision.stack=2
actions.execute+=/execute,if=buff.memory_of_lucid_dreams.up|buff.deadly_calm.up|(buff.test_of_might.up&cooldown.memory_of_lucid_dreams.remains>94)
actions.execute+=/overpower
actions.execute+=/execute
actions.five_target=skullsplitter,if=rage<60&(!talent.deadly_calm.enabled|buff.deadly_calm.down)
actions.five_target+=/ravager,if=(!talent.warbreaker.enabled|cooldown.warbreaker.remains<2)
actions.five_target+=/colossus_smash,if=debuff.colossus_smash.down
actions.five_target+=/warbreaker,if=debuff.colossus_smash.down
actions.five_target+=/bladestorm,if=buff.sweeping_strikes.down&(!talent.deadly_calm.enabled|buff.deadly_calm.down)&((debuff.colossus_smash.remains>4.5&!azerite.test_of_might.enabled)|buff.test_of_might.up)
actions.five_target+=/deadly_calm
actions.five_target+=/cleave
actions.five_target+=/execute,if=(!talent.cleave.enabled&dot.deep_wounds.remains<2)|(buff.sudden_death.react|buff.stone_heart.react)&(buff.sweeping_strikes.up|cooldown.sweeping_strikes.remains>8)
actions.five_target+=/mortal_strike,if=(!talent.cleave.enabled&dot.deep_wounds.remains<2)|buff.sweeping_strikes.up&buff.overpower.stack=2&(talent.dreadnaught.enabled|buff.executioners_precision.stack=2)
actions.five_target+=/whirlwind,if=debuff.colossus_smash.up|(buff.crushing_assault.up&talent.fervor_of_battle.enabled)
actions.five_target+=/whirlwind,if=buff.deadly_calm.up|rage>60
actions.five_target+=/overpower
actions.five_target+=/whirlwind
actions.hac=rend,if=remains<=duration*0.3&(!raid_event.adds.up|buff.sweeping_strikes.up)
actions.hac+=/skullsplitter,if=rage<60&(cooldown.deadly_calm.remains>3|!talent.deadly_calm.enabled)
actions.hac+=/deadly_calm,if=(cooldown.bladestorm.remains>6|talent.ravager.enabled&cooldown.ravager.remains>6)&(cooldown.colossus_smash.remains<2|(talent.warbreaker.enabled&cooldown.warbreaker.remains<2))
actions.hac+=/ravager,if=(raid_event.adds.up|raid_event.adds.in>target.time_to_die)&(cooldown.colossus_smash.remains<2|(talent.warbreaker.enabled&cooldown.warbreaker.remains<2))
actions.hac+=/colossus_smash,if=raid_event.adds.up|raid_event.adds.in>40|(raid_event.adds.in>20&talent.anger_management.enabled)
actions.hac+=/warbreaker,if=raid_event.adds.up|raid_event.adds.in>40|(raid_event.adds.in>20&talent.anger_management.enabled)
actions.hac+=/bladestorm,if=(debuff.colossus_smash.up&raid_event.adds.in>target.time_to_die)|raid_event.adds.up&((debuff.colossus_smash.remains>4.5&!azerite.test_of_might.enabled)|buff.test_of_might.up)
actions.hac+=/overpower,if=!raid_event.adds.up|(raid_event.adds.up&azerite.seismic_wave.enabled)
actions.hac+=/cleave,if=spell_targets.whirlwind>2
actions.hac+=/execute,if=!raid_event.adds.up|(!talent.cleave.enabled&dot.deep_wounds.remains<2)|buff.sudden_death.react
actions.hac+=/mortal_strike,if=!raid_event.adds.up|(!talent.cleave.enabled&dot.deep_wounds.remains<2)
actions.hac+=/whirlwind,if=raid_event.adds.up
actions.hac+=/overpower
actions.hac+=/whirlwind,if=talent.fervor_of_battle.enabled
actions.hac+=/slam,if=!talent.fervor_of_battle.enabled&!raid_event.adds.up
actions.single_target=rend,if=remains<=duration*0.3&debuff.colossus_smash.down
actions.single_target+=/skullsplitter,if=rage<60&buff.deadly_calm.down&buff.memory_of_lucid_dreams.down
actions.single_target+=/ravager,if=!buff.deadly_calm.up&(cooldown.colossus_smash.remains<2|(talent.warbreaker.enabled&cooldown.warbreaker.remains<2))
actions.single_target+=/colossus_smash
actions.single_target+=/warbreaker
actions.single_target+=/deadly_calm
actions.single_target+=/execute,if=buff.sudden_death.react
actions.single_target+=/bladestorm,if=cooldown.mortal_strike.remains&(!talent.deadly_calm.enabled|buff.deadly_calm.down)&((debuff.colossus_smash.up&!azerite.test_of_might.enabled)|buff.test_of_might.up)&buff.memory_of_lucid_dreams.down&rage<40
actions.single_target+=/cleave,if=spell_targets.whirlwind>2
actions.single_target+=/overpower,if=(rage<30&buff.memory_of_lucid_dreams.up&debuff.colossus_smash.up)|(rage<70&buff.memory_of_lucid_dreams.down)
actions.single_target+=/mortal_strike
actions.single_target+=/whirlwind,if=talent.fervor_of_battle.enabled&(buff.memory_of_lucid_dreams.up|debuff.colossus_smash.up|buff.deadly_calm.up)
actions.single_target+=/overpower
actions.single_target+=/whirlwind,if=talent.fervor_of_battle.enabled&(buff.test_of_might.up|debuff.colossus_smash.down&buff.test_of_might.down&rage>60)
actions.single_target+=/slam,if=!talent.fervor_of_battle.enabled
]])

TJ:RegisterActionProfileList('simc::warrior::fury', 'Simulationcraft Warrior Profile: Fury', 1, 2, [[
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/use_item,name=azsharas_font_of_power
actions.precombat+=/worldvein_resonance
actions.precombat+=/memory_of_lucid_dreams
actions.precombat+=/guardian_of_azeroth
actions.precombat+=/recklessness
actions.precombat+=/potion
actions=auto_attack
actions+=/charge
actions+=/run_action_list,name=movement,if=movement.distance>5
actions+=/heroic_leap,if=(raid_event.movement.distance>25&raid_event.movement.in>45)
actions+=/potion,if=buff.guardian_of_azeroth.up|(!essence.condensed_lifeforce.major&target.time_to_die=60)
actions+=/rampage,if=cooldown.recklessness.remains<3
actions+=/blood_of_the_enemy,if=buff.recklessness.up
actions+=/purifying_blast,if=!buff.recklessness.up&!buff.siegebreaker.up
actions+=/ripple_in_space,if=!buff.recklessness.up&!buff.siegebreaker.up
actions+=/worldvein_resonance,if=!buff.recklessness.up&!buff.siegebreaker.up
actions+=/focused_azerite_beam,if=!buff.recklessness.up&!buff.siegebreaker.up
actions+=/reaping_flames,if=!buff.recklessness.up&!buff.siegebreaker.up
actions+=/concentrated_flame,if=!buff.recklessness.up&!buff.siegebreaker.up&dot.concentrated_flame_burn.remains=0
actions+=/the_unbound_force,if=buff.reckless_force.up
actions+=/guardian_of_azeroth,if=!buff.recklessness.up&(target.time_to_die>195|target.health.pct<20)
actions+=/memory_of_lucid_dreams,if=!buff.recklessness.up
actions+=/recklessness,if=!essence.condensed_lifeforce.major&!essence.blood_of_the_enemy.major|cooldown.guardian_of_azeroth.remains>1|buff.guardian_of_azeroth.up|cooldown.blood_of_the_enemy.remains<gcd
actions+=/whirlwind,if=spell_targets.whirlwind>1&!buff.meat_cleaver.up
actions+=/blood_fury,if=buff.recklessness.up
actions+=/berserking,if=buff.recklessness.up
actions+=/lights_judgment,if=buff.recklessness.down&debuff.siegebreaker.down
actions+=/fireblood,if=buff.recklessness.up
actions+=/ancestral_call,if=buff.recklessness.up
actions+=/bag_of_tricks,if=buff.recklessness.down&debuff.siegebreaker.down&buff.enrage.up
actions+=/run_action_list,name=single_target
actions.movement=heroic_leap
actions.single_target=siegebreaker
actions.single_target+=/rampage,if=(buff.recklessness.up|buff.memory_of_lucid_dreams.up)|(talent.frothing_berserker.enabled|talent.carnage.enabled&(buff.enrage.remains<gcd|rage>90)|talent.massacre.enabled&(buff.enrage.remains<gcd|rage>90))
actions.single_target+=/execute
actions.single_target+=/furious_slash,if=!buff.bloodlust.up&buff.furious_slash.remains<3
actions.single_target+=/bladestorm,if=prev_gcd.1.rampage
actions.single_target+=/bloodthirst,if=buff.enrage.down|azerite.cold_steel_hot_blood.rank>1
actions.single_target+=/dragon_roar,if=buff.enrage.up
actions.single_target+=/raging_blow,if=charges=2
actions.single_target+=/bloodthirst
actions.single_target+=/raging_blow,if=talent.carnage.enabled|(talent.massacre.enabled&rage<80)|(talent.frothing_berserker.enabled&rage<90)
actions.single_target+=/furious_slash,if=talent.furious_slash.enabled
actions.single_target+=/whirlwind
]])

TJ:RegisterActionProfileList('simc::warrior::protection', 'Simulationcraft Warrior Profile: Protection', 1, 3, [[
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/use_item,name=azsharas_font_of_power
actions.precombat+=/worldvein_resonance
actions.precombat+=/memory_of_lucid_dreams
actions.precombat+=/guardian_of_azeroth
actions.precombat+=/potion
actions=auto_attack
actions+=/intercept,if=time=0
actions+=/use_items,if=cooldown.avatar.remains<=gcd|buff.avatar.up
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent
actions+=/lights_judgment
actions+=/fireblood
actions+=/ancestral_call
actions+=/bag_of_tricks
actions+=/potion,if=buff.avatar.up|target.time_to_die<25
actions+=/ignore_pain,if=rage.deficit<25+20*talent.booming_voice.enabled*cooldown.demoralizing_shout.ready
actions+=/worldvein_resonance,if=cooldown.avatar.remains<=2
actions+=/ripple_in_space
actions+=/memory_of_lucid_dreams
actions+=/concentrated_flame,if=buff.avatar.down&!dot.concentrated_flame_burn.remains>0|essence.the_crucible_of_flame.rank<3
actions+=/last_stand,if=cooldown.anima_of_death.remains<=2
actions+=/avatar
actions+=/run_action_list,name=aoe,if=spell_targets.thunder_clap>=3
actions+=/call_action_list,name=st
actions.aoe=thunder_clap
actions.aoe+=/memory_of_lucid_dreams,if=buff.avatar.down
actions.aoe+=/demoralizing_shout,if=talent.booming_voice.enabled
actions.aoe+=/anima_of_death,if=buff.last_stand.up
actions.aoe+=/dragon_roar
actions.aoe+=/revenge
actions.aoe+=/use_item,name=grongs_primal_rage,if=buff.avatar.down|cooldown.thunder_clap.remains>=4
actions.aoe+=/ravager
actions.aoe+=/shield_block,if=cooldown.shield_slam.ready&buff.shield_block.down
actions.aoe+=/shield_slam
actions.st=thunder_clap,if=spell_targets.thunder_clap=2&talent.unstoppable_force.enabled&buff.avatar.up
actions.st+=/shield_block,if=cooldown.shield_slam.ready&buff.shield_block.down
actions.st+=/shield_slam,if=buff.shield_block.up
actions.st+=/thunder_clap,if=(talent.unstoppable_force.enabled&buff.avatar.up)
actions.st+=/demoralizing_shout,if=talent.booming_voice.enabled
actions.st+=/anima_of_death,if=buff.last_stand.up
actions.st+=/shield_slam
actions.st+=/use_item,name=ashvanes_razor_coral,target_if=debuff.razor_coral_debuff.stack=0
actions.st+=/use_item,name=ashvanes_razor_coral,if=debuff.razor_coral_debuff.stack>7&(cooldown.avatar.remains<5|buff.avatar.up)
actions.st+=/dragon_roar
actions.st+=/thunder_clap
actions.st+=/revenge
actions.st+=/use_item,name=grongs_primal_rage,if=buff.avatar.down|cooldown.shield_slam.remains>=4
actions.st+=/ravager
actions.st+=/devastate
]])

