if select(3, UnitClass('player')) ~= 1 then return end
local Engine = LibStub('LibSandbox-5.0'):GetSandbox('TJ5').Engine

Engine:RegisterActionProfileList('simc::warrior::arms', 'Simulationcraft Warrior Profile: Arms', 1, 1, [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=lavish_suramar_feast
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war
actions=charge
actions+=/auto_attack
actions+=/potion,name=old_war,if=(!talent.avatar.enabled|buff.avatar.up)&buff.battle_cry.up&debuff.colossus_smash.up|target.time_to_die<=26
actions+=/blood_fury,if=buff.battle_cry.up|target.time_to_die<=16
actions+=/berserking,if=buff.battle_cry.up|target.time_to_die<=11
actions+=/arcane_torrent,if=buff.battle_cry_deadly_calm.down&rage.deficit>40&cooldown.battle_cry.remains
actions+=/avatar,if=gcd.remains<0.25&(buff.battle_cry.up|cooldown.battle_cry.remains<15)|target.time_to_die<=20
actions+=/battle_cry,if=target.time_to_die<=6|(gcd.remains<=0.5&prev_gcd.1.ravager)|!talent.ravager.enabled&!gcd.remains&target.debuff.colossus_smash.remains>=5&(!cooldown.bladestorm.remains|!set_bonus.tier20_4pc)&(!talent.rend.enabled|dot.rend.remains>4)
actions+=/run_action_list,name=cleave,if=spell_targets.whirlwind>=2&talent.sweeping_strikes.enabled
actions+=/run_action_list,name=aoe,if=spell_targets.whirlwind>=5&!talent.sweeping_strikes.enabled
actions+=/run_action_list,name=execute,target_if=target.health.pct<=20&spell_targets.whirlwind<5
actions+=/run_action_list,name=single,if=target.health.pct>20
actions.aoe=warbreaker,if=(cooldown.bladestorm.up|cooldown.bladestorm.remains<=gcd)&(cooldown.battle_cry.up|cooldown.battle_cry.remains<=gcd)
actions.aoe+=/bladestorm,if=buff.battle_cry.up&(set_bonus.tier20_4pc|equipped.the_great_storms_eye)
actions.aoe+=/colossus_smash,if=buff.in_for_the_kill.down&talent.in_for_the_kill.enabled
actions.aoe+=/colossus_smash,cycle_targets=1,if=debuff.colossus_smash.down&spell_targets.whirlwind<=10
actions.aoe+=/cleave,if=spell_targets.whirlwind>=5
actions.aoe+=/whirlwind,if=spell_targets.whirlwind>=5&buff.cleave.up
actions.aoe+=/whirlwind,if=spell_targets.whirlwind>=7
actions.aoe+=/colossus_smash,if=buff.shattered_defenses.down
actions.aoe+=/execute,if=buff.stone_heart.react
actions.aoe+=/mortal_strike,if=buff.shattered_defenses.up|buff.executioners_precision.down
actions.aoe+=/rend,cycle_targets=1,if=remains<=duration*0.3&spell_targets.whirlwind<=3
actions.aoe+=/cleave
actions.aoe+=/whirlwind
actions.cleave=mortal_strike
actions.cleave+=/execute,if=buff.stone_heart.react
actions.cleave+=/colossus_smash,if=buff.shattered_defenses.down&buff.precise_strikes.down
actions.cleave+=/warbreaker,if=buff.shattered_defenses.down
actions.cleave+=/focused_rage,if=rage>100|buff.battle_cry_deadly_calm.up
actions.cleave+=/whirlwind,if=talent.fervor_of_battle.enabled&(debuff.colossus_smash.up|rage.deficit<50)&(!talent.focused_rage.enabled|buff.battle_cry_deadly_calm.up|buff.cleave.up)
actions.cleave+=/rend,if=remains<=duration*0.3
actions.cleave+=/bladestorm
actions.cleave+=/cleave
actions.cleave+=/whirlwind,if=rage>40|buff.cleave.up
actions.cleave+=/shockwave
actions.cleave+=/storm_bolt
actions.execute=bladestorm,if=buff.battle_cry.up&(set_bonus.tier20_4pc|equipped.the_great_storms_eye)
actions.execute+=/colossus_smash,if=buff.shattered_defenses.down&(buff.battle_cry.down|buff.battle_cry.remains>gcd.max)
actions.execute+=/warbreaker,if=(raid_event.adds.in>90|!raid_event.adds.exists)&cooldown.mortal_strike.remains<=gcd.remains&buff.shattered_defenses.down&buff.executioners_precision.stack=2
actions.execute+=/focused_rage,if=rage.deficit<35
actions.execute+=/rend,if=remains<5&cooldown.battle_cry.remains<2&(cooldown.bladestorm.remains<2|!set_bonus.tier20_4pc)
actions.execute+=/ravager,if=cooldown.battle_cry.remains<=gcd&debuff.colossus_smash.remains>6
actions.execute+=/mortal_strike,if=buff.executioners_precision.stack=2&buff.shattered_defenses.up
actions.execute+=/overpower,if=rage<40
actions.execute+=/execute,if=buff.shattered_defenses.down|rage>=40|talent.dauntless.enabled&rage>=36
actions.execute+=/bladestorm,interrupt=1,if=(raid_event.adds.in>90|!raid_event.adds.exists|spell_targets.bladestorm_mh>desired_targets)&!set_bonus.tier20_4pc
actions.single=bladestorm,if=buff.battle_cry.up&set_bonus.tier20_4pc
actions.single+=/colossus_smash,if=buff.shattered_defenses.down
actions.single+=/warbreaker,if=(raid_event.adds.in>90|!raid_event.adds.exists)&((talent.fervor_of_battle.enabled&debuff.colossus_smash.remains<gcd)|!talent.fervor_of_battle.enabled&((buff.stone_heart.up|cooldown.mortal_strike.remains<=gcd.remains)&buff.shattered_defenses.down))
actions.single+=/focused_rage,if=!buff.battle_cry_deadly_calm.up&buff.focused_rage.stack<3&!cooldown.colossus_smash.up&(rage>=130|debuff.colossus_smash.down|talent.anger_management.enabled&cooldown.battle_cry.remains<=8)
actions.single+=/rend,if=remains<=gcd.max|remains<5&cooldown.battle_cry.remains<2&(cooldown.bladestorm.remains<2|!set_bonus.tier20_4pc)
actions.single+=/ravager,if=cooldown.battle_cry.remains<=gcd&debuff.colossus_smash.remains>6
actions.single+=/execute,if=buff.stone_heart.react
actions.single+=/overpower,if=buff.battle_cry.down
actions.single+=/mortal_strike,if=buff.shattered_defenses.up|buff.executioners_precision.down
actions.single+=/rend,if=remains<=duration*0.3
actions.single+=/whirlwind,if=spell_targets.whirlwind>1|talent.fervor_of_battle.enabled
actions.single+=/slam,if=spell_targets.whirlwind=1&!talent.fervor_of_battle.enabled&(rage>=52|!talent.rend.enabled|!talent.ravager.enabled)
actions.single+=/overpower
actions.single+=/bladestorm,if=(raid_event.adds.in>90|!raid_event.adds.exists)&!set_bonus.tier20_4pc
]])

Engine:RegisterActionProfileList('simc::warrior::fury', 'Simulationcraft Warrior Profile: Fury', 1, 2, [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=lavish_suramar_feast
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war
actions=auto_attack
actions+=/charge
actions+=/run_action_list,name=movement,if=movement.distance>5
actions+=/heroic_leap,if=(raid_event.movement.distance>25&raid_event.movement.in>45)|!raid_event.movement.exists
actions+=/potion,name=old_war,if=buff.battle_cry.up&(buff.avatar.up|!talent.avatar.enabled)
actions+=/dragon_roar,if=(equipped.convergence_of_fates&cooldown.battle_cry.remains<2)|!equipped.convergence_of_fates&(!cooldown.battle_cry.remains<=10|cooldown.battle_cry.remains<2)
actions+=/rampage,if=cooldown.battle_cry.remains<4&target.health.pct>20
actions+=/bloodthirst,if=equipped.kazzalax_fujiedas_fury&buff.fujiedas_fury.down
actions+=/avatar,if=buff.battle_cry.remains>6|cooldown.battle_cry.remains<10|(target.time_to_die<(cooldown.battle_cry.remains+10))
actions+=/use_item,name=umbral_moonglaives,if=equipped.umbral_moonglaives&(cooldown.battle_cry.remains>gcd&cooldown.battle_cry.remains<2|cooldown.battle_cry.remains=0)
actions+=/battle_cry,if=gcd.remains=0&talent.reckless_abandon.enabled&(equipped.umbral_moonglaives&(prev_off_gcd.umbral_moonglaives|(trinket.cooldown.remains>3&trinket.cooldown.remains<90))|!equipped.umbral_moonglaives)
actions+=/battle_cry,if=gcd.remains=0&talent.bladestorm.enabled&(raid_event.adds.in>90|!raid_event.adds.exists|spell_targets.bladestorm_mh>desired_targets)
actions+=/battle_cry,if=gcd.remains=0&buff.dragon_roar.up&(cooldown.bloodthirst.remains=0|buff.enrage.remains>cooldown.bloodthirst.remains)
actions+=/bloodbath,if=buff.dragon_roar.up|!talent.dragon_roar.enabled&buff.battle_cry.up
actions+=/blood_fury,if=buff.battle_cry.up
actions+=/berserking,if=buff.battle_cry.up
actions+=/arcane_torrent,if=rage<rage.max-40
actions+=/run_action_list,name=cooldowns,if=buff.battle_cry.up&spell_targets.whirlwind=1
actions+=/call_action_list,name=three_targets,if=target.health.pct>20&(spell_targets.whirlwind=3|spell_targets.whirlwind=4)
actions+=/call_action_list,name=aoe,if=spell_targets.whirlwind>4
actions+=/run_action_list,name=execute,if=target.health.pct<20
actions+=/run_action_list,name=single_target,if=target.health.pct>20
actions.aoe=bloodthirst,if=buff.enrage.down|rage<90
actions.aoe+=/bladestorm,if=buff.enrage.remains>2&(raid_event.adds.in>90|!raid_event.adds.exists|spell_targets.bladestorm_mh>desired_targets)
actions.aoe+=/whirlwind,if=buff.meat_cleaver.down
actions.aoe+=/rampage,if=buff.meat_cleaver.up&(buff.enrage.down&!talent.frothing_berserker.enabled|buff.massacre.react|rage>=100)
actions.aoe+=/bloodthirst
actions.aoe+=/whirlwind
actions.cooldowns=rampage,if=talent.massacre.enabled&buff.massacre.react&buff.enrage.remains<1
actions.cooldowns+=/bloodthirst,if=target.health.pct<20&buff.enrage.remains<1
actions.cooldowns+=/execute,if=equipped.draught_of_souls&cooldown.draught_of_souls.remains<1&buff.juggernaut.remains<3
actions.cooldowns+=/odyns_fury,if=buff.enrage.up&cooldown.raging_blow.remains>0&target.health.pct>20
actions.cooldowns+=/execute
actions.cooldowns+=/raging_blow,if=talent.inner_rage.enabled&buff.enrage.up
actions.cooldowns+=/rampage,if=talent.reckless_abandon.enabled&!talent.frothing_berserker.enabled|(talent.frothing_berserker.enabled&rage>=100)
actions.cooldowns+=/berserker_rage,if=talent.outburst.enabled&buff.enrage.down&buff.battle_cry.up
actions.cooldowns+=/bloodthirst,if=buff.enrage.remains<1&!talent.outburst.enabled
actions.cooldowns+=/raging_blow
actions.cooldowns+=/bloodthirst
actions.cooldowns+=/whirlwind,if=buff.wrecking_ball.react&buff.enrage.up
actions.cooldowns+=/furious_slash
actions.execute=bloodthirst,if=buff.fujiedas_fury.up&buff.fujiedas_fury.remains<2
actions.execute+=/execute,if=artifact.juggernaut.enabled&(!buff.juggernaut.up|buff.juggernaut.remains<2)|buff.stone_heart.react
actions.execute+=/furious_slash,if=talent.frenzy.enabled&buff.frenzy.remains<=2
actions.execute+=/execute,if=cooldown.battle_cry.remains<5
actions.execute+=/rampage,if=buff.massacre.react&buff.enrage.remains<1
actions.execute+=/execute
actions.execute+=/bloodthirst
actions.execute+=/furious_slash,if=set_bonus.tier19_2pc
actions.execute+=/raging_blow
actions.execute+=/odyns_fury,if=buff.enrage.up&rage<100
actions.execute+=/furious_slash
actions.movement=heroic_leap
actions.single_target=bloodthirst,if=buff.fujiedas_fury.up&buff.fujiedas_fury.remains<2
actions.single_target+=/furious_slash,if=talent.frenzy.enabled&(buff.frenzy.down|buff.frenzy.remains<=2)
actions.single_target+=/raging_blow,if=buff.enrage.up&talent.inner_rage.enabled
actions.single_target+=/rampage,if=target.health.pct>21&((buff.enrage.down&!talent.frothing_berserker.enabled)|buff.massacre.react|rage>=100)
actions.single_target+=/execute,if=buff.stone_heart.react&((talent.inner_rage.enabled&cooldown.raging_blow.remains>1)|buff.enrage.up)
actions.single_target+=/bloodthirst
actions.single_target+=/furious_slash,if=set_bonus.tier19_2pc&!talent.inner_rage.enabled
actions.single_target+=/raging_blow
actions.single_target+=/whirlwind,if=buff.wrecking_ball.react&buff.enrage.up
actions.single_target+=/furious_slash
actions.three_targets=execute,if=buff.stone_heart.react
actions.three_targets+=/rampage,if=buff.meat_cleaver.up&((buff.enrage.down&!talent.frothing_berserker.enabled)|(rage>=100&talent.frothing_berserker.enabled))|buff.massacre.react
actions.three_targets+=/raging_blow,if=talent.inner_rage.enabled
actions.three_targets+=/bloodthirst
actions.three_targets+=/whirlwind
]])

Engine:RegisterActionProfileList('simc::warrior::protection', 'Simulationcraft Warrior Profile: Protection', 1, 3, [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=lavish_suramar_feast
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=old_war
actions=auto_attack
actions+=/intercept
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent
actions+=/call_action_list,name=prot
actions.prot=potion,name=old_war,if=target.time_to_die<25
actions.prot+=/battle_cry,if=cooldown.shield_slam.remains=0
actions.prot+=/demoralizing_shout
actions.prot+=/ravager,if=talent.ravager.enabled
actions.prot+=/shield_block,if=cooldown.shield_slam.remains=0
actions.prot+=/ignore_pain,if=(!talent.vengeance.enabled&buff.renewed_fury.remains<1.5)|(!talent.vengeance.enabled&rage.deficit>=40)|(buff.vengeance_ignore_pain.up)|(talent.vengeance.enabled&!buff.vengeance_ignore_pain.up&!buff.vengeance_revenge.up&rage<30&!buff.revenge.react)
actions.prot+=/shield_slam
actions.prot+=/revenge,if=(!talent.vengeance.enabled)|(talent.vengeance.enabled&buff.revenge.react&!buff.vengeance_ignore_pain.up)|(buff.vengeance_revenge.up)|(talent.vengeance.enabled&!buff.vengeance_ignore_pain.up&!buff.vengeance_revenge.up&rage>=30)
actions.prot+=/thunder_clap
actions.prot+=/devastate
]])

