local _, internal = ...
internal.apls = internal.apls or {}

internal.apls["legion-dev::Tier19P::Warrior_Arms_T19P"] = [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions=charge
actions+=/auto_attack
actions+=/potion,name=deadly_grace,if=(target.health.pct<20&buff.battle_cry.up)|target.time_to_die<25
actions+=/battle_cry,sync=colossus_smash
actions+=/battle_cry
actions+=/avatar,sync=colossus_smash
actions+=/avatar
actions+=/blood_fury,if=buff.battle_cry.up
actions+=/berserking,if=buff.battle_cry.up
actions+=/arcane_torrent,if=rage<rage.max-40
actions+=/use_item,name=gift_of_radiance
actions+=/heroic_leap,if=debuff.colossus_smash.up
actions+=/rend,if=remains<gcd
actions+=/hamstring,if=buff.battle_cry_deadly_calm.up
actions+=/colossus_smash,if=debuff.colossus_smash.down
actions+=/warbreaker,if=debuff.colossus_smash.down
actions+=/ravager
actions+=/overpower
actions+=/run_action_list,name=cleave,if=spell_targets.whirlwind>=2&talent.sweeping_strikes.enabled
actions+=/run_action_list,name=aoe,if=spell_targets.whirlwind>=2&!talent.sweeping_strikes.enabled
actions+=/run_action_list,name=single
actions.single=colossus_smash,if=buff.shattered_defenses.down&buff.precise_strikes.down
actions.single+=/warbreaker,if=buff.shattered_defenses.down
actions.single+=/execute,if=buff.stone_heart.react|buff.battle_cry_deadly_calm.up
actions.single+=/execute,if=debuff.colossus_smash.up&rage.deficit<60
actions.single+=/mortal_strike
actions.single+=/focused_rage,if=(buff.focused_rage.stack<3&((talent.dauntless.enabled&rage>27)|(!talent.dauntless.enabled&rage>34)))|buff.battle_cry_deadly_calm.up
actions.single+=/slam,if=target.health.pct>20&!talent.fervor_of_battle.enabled&(debuff.colossus_smash.up|rage.deficit<40|buff.battle_cry_deadly_calm.up)&(!talent.focused_rage.enabled|buff.battle_cry_deadly_calm.up)
actions.single+=/whirlwind,if=target.health.pct>20&talent.fervor_of_battle.enabled&(debuff.colossus_smash.up|rage.deficit<50)&(!talent.focused_rage.enabled|buff.battle_cry_deadly_calm.up|buff.cleave.up)
actions.single+=/rend,if=remains<=duration*0.3
actions.single+=/whirlwind,if=target.health.pct>20&talent.fervor_of_battle.enabled&(!talent.focused_rage.enabled|rage.deficit<20|buff.focused_rage.stack=3)
actions.single+=/slam,if=target.health.pct>20&!talent.fervor_of_battle.enabled&(!talent.focused_rage.enabled|rage.deficit<20|buff.focused_rage.stack=3)
actions.single+=/execute,if=equipped.137060
actions.single+=/slam,if=equipped.137060
actions.single+=/shockwave
actions.single+=/storm_bolt
actions.single+=/bladestorm,if=raid_event.adds.in>90|!raid_event.adds.exists|spell_targets.bladestorm_mh>desired_targets
actions.cleave=mortal_strike
actions.cleave+=/execute,if=buff.stone_heart.react
actions.cleave+=/colossus_smash,if=buff.shattered_defenses.down&buff.precise_strikes.down
actions.cleave+=/warbreaker,if=buff.shattered_defenses.down
actions.cleave+=/focused_rage,if=buff.shattered_defenses.down
actions.cleave+=/whirlwind,if=talent.fervor_of_battle.enabled&(debuff.colossus_smash.up|rage.deficit<50)&(!talent.focused_rage.enabled|buff.battle_cry_deadly_calm.up|buff.cleave.up)
actions.cleave+=/rend,if=remains<=duration*0.3
actions.cleave+=/bladestorm
actions.cleave+=/cleave
actions.cleave+=/whirlwind,if=rage>=100|buff.focused_rage.stack=3
actions.cleave+=/shockwave
actions.cleave+=/storm_bolt
actions.aoe=mortal_strike
actions.aoe+=/execute,if=buff.stone_heart.react
actions.aoe+=/colossus_smash,if=buff.shattered_defenses.down&buff.precise_strikes.down
actions.aoe+=/warbreaker,if=buff.shattered_defenses.down
actions.aoe+=/whirlwind,if=talent.fervor_of_battle.enabled&(debuff.colossus_smash.up|rage.deficit<50)&(!talent.focused_rage.enabled|buff.battle_cry_deadly_calm.up|buff.cleave.up)
actions.aoe+=/rend,if=remains<=duration*0.3
actions.aoe+=/bladestorm
actions.aoe+=/cleave
actions.aoe+=/whirlwind,if=rage>=60
actions.aoe+=/shockwave
actions.aoe+=/storm_bolt
]]

internal.apls["legion-dev::Tier19P::Warrior_Fury_T19P"] = [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions=auto_attack
actions+=/charge
actions+=/run_action_list,name=movement,if=movement.distance>5
actions+=/heroic_leap,if=(raid_event.movement.distance>25&raid_event.movement.in>45)|!raid_event.movement.exists
actions+=/use_item,name=faulty_countermeasure,if=(spell_targets.whirlwind>1|!raid_event.adds.exists)&((talent.bladestorm.enabled&cooldown.bladestorm.remains=0)|buff.battle_cry.up|target.time_to_die<25)
actions+=/potion,name=deadly_grace,if=(target.health.pct<20&buff.battle_cry.up)|target.time_to_die<30
actions+=/battle_cry,if=(artifact.odyns_fury.enabled&cooldown.odyns_fury.remains=0&(cooldown.bloodthirst.remains=0|(buff.enrage.remains>cooldown.bloodthirst.remains)))|!artifact.odyns_fury.enabled
actions+=/avatar,if=buff.battle_cry.up|(target.time_to_die<(cooldown.battle_cry.remains+10))
actions+=/bloodbath,if=buff.dragon_roar.up|(!talent.dragon_roar.enabled&(buff.battle_cry.up|cooldown.battle_cry.remains>10))
actions+=/blood_fury,if=buff.battle_cry.up
actions+=/berserking,if=buff.battle_cry.up
actions+=/arcane_torrent,if=rage<rage.max-40
actions+=/call_action_list,name=two_targets,if=spell_targets.whirlwind=2|spell_targets.whirlwind=3
actions+=/call_action_list,name=aoe,if=spell_targets.whirlwind>3
actions+=/call_action_list,name=single_target
actions.movement=heroic_leap
actions.single_target=odyns_fury,if=buff.battle_cry.up|target.time_to_die<cooldown.battle_cry.remains
actions.single_target+=/execute,if=artifact.juggernaut.enabled&(!buff.juggernaut.up|buff.juggernaut.remains<2)
actions.single_target+=/berserker_rage,if=talent.outburst.enabled&cooldown.dragon_roar.remains=0&buff.enrage.down
actions.single_target+=/rampage,if=rage>95|buff.massacre.react
actions.single_target+=/whirlwind,if=!talent.inner_rage.enabled&buff.wrecking_ball.react
actions.single_target+=/raging_blow,if=buff.enrage.up
actions.single_target+=/whirlwind,if=buff.wrecking_ball.react&buff.enrage.up
actions.single_target+=/execute,if=buff.enrage.up|buff.battle_cry.up|buff.stone_heart.react||(buff.juggernaut.up&buff.juggernaut.remains<3)
actions.single_target+=/bloodthirst
actions.single_target+=/raging_blow
actions.single_target+=/dragon_roar,if=!talent.bloodbath.enabled&(cooldown.battle_cry.remains<1|cooldown.battle_cry.remains>10)|talent.bloodbath.enabled&cooldown.bloodbath.remains=0
actions.single_target+=/rampage,if=(target.health.pct>20&(cooldown.battle_cry.remains>3|buff.battle_cry.up|rage>90))
actions.single_target+=/execute,if=rage>50|buff.battle_cry.up|buff.stone_heart.react|target.time_to_die<20
actions.single_target+=/furious_slash
actions.two_targets=whirlwind,if=buff.meat_cleaver.down
actions.two_targets+=/call_action_list,name=bladestorm
actions.two_targets+=/rampage,if=buff.enrage.down|(rage=100&buff.juggernaut.down)|buff.massacre.up
actions.two_targets+=/bloodthirst,if=buff.enrage.down
actions.two_targets+=/raging_blow,if=talent.inner_rage.enabled&spell_targets.whirlwind=2
actions.two_targets+=/whirlwind,if=spell_targets.whirlwind>2
actions.two_targets+=/dragon_roar
actions.two_targets+=/bloodthirst
actions.two_targets+=/whirlwind
actions.aoe=bloodthirst,if=buff.enrage.down|rage<50
actions.aoe+=/call_action_list,name=bladestorm
actions.aoe+=/whirlwind,if=buff.enrage.up
actions.aoe+=/dragon_roar
actions.aoe+=/rampage,if=buff.meat_cleaver.up
actions.aoe+=/bloodthirst
actions.aoe+=/whirlwind
actions.bladestorm=bladestorm,if=buff.enrage.remains>2&(raid_event.adds.in>90|!raid_event.adds.exists|spell_targets.bladestorm_mh>desired_targets)
]]

internal.apls["legion-dev::Tier19P::Warrior_Protection_T19P"] = [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=unbending_potion
actions=intercept
actions+=/auto_attack
actions+=/use_item,name=horn_of_valor
actions+=/use_item,name=coagulated_nightwell_residue
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent
actions+=/call_action_list,name=prot
actions.prot=shield_block,if=!buff.neltharions_fury.up
actions.prot+=/ignore_pain,if=buff.ignore_pain.up&rage>=30|(talent.vengeance.enabled&rage>=20&!buff.ignore_pain.up&!buff.focused_rage.up)|!talent.vengeance.enabled
actions.prot+=/focused_rage,if=(talent.vengeance.enabled&buff.vengeance_focused_rage.up&!buff.vengeance_ignore_pain.up)|(talent.vengeance.enabled&buff.vengeance_focused_rage.up&!buff.vengeance_ignore_pain.up&buff.ultimatum.up)
actions.prot+=/demoralizing_shout,if=incoming_damage_2500ms>health.max*0.20
actions.prot+=/shield_wall,if=incoming_damage_2500ms>health.max*0.50
actions.prot+=/last_stand,if=incoming_damage_2500ms>health.max*0.50&!cooldown.shield_wall.remains=0
actions.prot+=/potion,name=unbending_potion,if=(incoming_damage_2500ms>health.max*0.15&!buff.unbending_potion.up)|target.time_to_die<=25
actions.prot+=/call_action_list,name=prot_aoe,if=spell_targets.thunder_clap>=3
actions.prot+=/focused_rage,if=talent.ultimatum.enabled&buff.ultimatum.up&!talent.vengeance.enabled
actions.prot+=/battle_cry
actions.prot+=/demoralizing_shout,if=talent.booming_voice.enabled&rage<=50
actions.prot+=/ravager,if=talent.ravager.enabled
actions.prot+=/neltharions_fury,if=buff.battle_cry.up
actions.prot+=/shield_slam
actions.prot+=/revenge
actions.prot+=/devastate
actions.prot_aoe=focused_rage,if=talent.ultimatum.enabled&buff.ultimatum.up&!talent.vengeance.enabled
actions.prot_aoe+=/battle_cry
actions.prot_aoe+=/demoralizing_shout,if=talent.booming_voice.enabled&rage<=50
actions.prot_aoe+=/ravager,if=talent.ravager.enabled
actions.prot_aoe+=/neltharions_fury,if=buff.battle_cry.up
actions.prot_aoe+=/shield_slam
actions.prot_aoe+=/revenge
actions.prot_aoe+=/thunder_clap
actions.prot_aoe+=/devastate
]]

