local _, internal = ...
internal.apls = internal.apls or {}

internal.apls["legion-dev::Tier19P::Death_Knight_Frost_T19P"] = [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=the_hungry_magister
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions=auto_attack
actions+=/arcane_torrent,if=runic_power.deficit>20
actions+=/blood_fury,if=!talent.breath_of_sindragosa.enabled|dot.breath_of_sindragosa.ticking
actions+=/berserking
actions+=/use_item,slot=trinket1
actions+=/potion,type=deadly_grace
actions+=/pillar_of_frost
actions+=/sindragosas_fury
actions+=/obliteration
actions+=/breath_of_sindragosa,if=runic_power>=50
actions+=/run_action_list,name=bos,if=dot.breath_of_sindragosa.ticking
actions+=/call_action_list,name=generic
actions.bos=howling_blast,target_if=!dot.frost_fever.ticking
actions.bos+=/call_action_list,name=core
actions.bos+=/horn_of_winter
actions.bos+=/empower_rune_weapon,if=runic_power<=70
actions.bos+=/hungering_rune_weapon
actions.bos+=/howling_blast,if=buff.rime.react
actions.generic=howling_blast,target_if=!dot.frost_fever.ticking
actions.generic+=/howling_blast,if=buff.rime.react
actions.generic+=/frost_strike,if=runic_power>=80
actions.generic+=/call_action_list,name=core
actions.generic+=/horn_of_winter,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/horn_of_winter,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/frost_strike,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/frost_strike,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/empower_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/hungering_rune_weapon,if=talent.breath_of_sindragosa.enabled&cooldown.breath_of_sindragosa.remains>15
actions.generic+=/empower_rune_weapon,if=!talent.breath_of_sindragosa.enabled
actions.generic+=/hungering_rune_weapon,if=!talent.breath_of_sindragosa.enabled
actions.core=glacial_advance
actions.core+=/frost_strike,if=buff.obliteration.up&!buff.killing_machine.react
actions.core+=/frostscythe,if=!talent.breath_of_sindragosa.enabled&(buff.killing_machine.react|spell_targets.frostscythe>=4)
actions.core+=/obliterate,if=buff.killing_machine.react
actions.core+=/remorseless_winter,if=spell_targets.remorseless_winter>=2
actions.core+=/obliterate
actions.core+=/frostscythe,if=talent.frozen_pulse.enabled
actions.core+=/howling_blast,if=talent.frozen_pulse.enabled
]]

internal.apls["legion-dev::Tier19P::Death_Knight_Unholy_T19P"] = [[
actions.precombat=flask,type=countless_armies
actions.precombat+=/food,type=the_hungry_magister
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/raise_dead
actions.precombat+=/army_of_the_dead
actions=auto_attack
actions+=/arcane_torrent,if=runic_power.deficit>20
actions+=/blood_fury
actions+=/berserking
actions+=/potion,name=deadly_grace,if=buff.unholy_strength.react
actions+=/outbreak,target_if=!dot.virulent_plague.ticking
actions+=/dark_transformation
actions+=/blighted_rune_weapon
actions+=/run_action_list,name=valkyr,if=talent.dark_arbiter.enabled&pet.valkyr_battlemaiden.active
actions+=/call_action_list,name=generic
actions.valkyr=death_coil
actions.valkyr+=/apocalypse,if=debuff.festering_wound.stack=8
actions.valkyr+=/festering_strike,if=debuff.festering_wound.stack<8&cooldown.apocalypse.remains<5
actions.valkyr+=/call_action_list,name=aoe,if=active_enemies>=2
actions.valkyr+=/festering_strike,if=debuff.festering_wound.stack<=3
actions.valkyr+=/scourge_strike,if=debuff.festering_wound.up
actions.valkyr+=/clawing_shadows,if=debuff.festering_wound.up
actions.generic=dark_arbiter,if=runic_power>80
actions.generic+=/summon_gargoyle
actions.generic+=/apocalypse,if=debuff.festering_wound.stack=8
actions.generic+=/death_coil,if=runic_power>80
actions.generic+=/death_coil,if=talent.dark_arbiter.enabled&buff.sudden_doom.react&cooldown.dark_arbiter.remains>5
actions.generic+=/death_coil,if=!talent.dark_arbiter.enabled&buff.sudden_doom.react
actions.generic+=/festering_strike,if=debuff.festering_wound.stack<8&cooldown.apocalypse.remains<5
actions.generic+=/soul_reaper,if=debuff.festering_wound.stack>=3
actions.generic+=/festering_strike,if=debuff.soul_reaper.up&!debuff.festering_wound.up
actions.generic+=/scourge_strike,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/clawing_shadows,if=debuff.soul_reaper.up&debuff.festering_wound.stack>=1
actions.generic+=/defile
actions.generic+=/call_action_list,name=aoe,if=active_enemies>=2
actions.generic+=/festering_strike,if=debuff.festering_wound.stack<=3
actions.generic+=/scourge_strike,if=buff.necrosis.react
actions.generic+=/clawing_shadows,if=buff.necrosis.react
actions.generic+=/scourge_strike,if=buff.unholy_strength.react
actions.generic+=/clawing_shadows,if=buff.unholy_strength.react
actions.generic+=/scourge_strike,if=rune>=2
actions.generic+=/clawing_shadows,if=rune>=2
actions.generic+=/death_coil,if=talent.shadow_infusion.enabled&talent.dark_arbiter.enabled&!buff.dark_transformation.up&cooldown.dark_arbiter.remains>15
actions.generic+=/death_coil,if=talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled&!buff.dark_transformation.up
actions.generic+=/death_coil,if=talent.dark_arbiter.enabled&cooldown.dark_arbiter.remains>15
actions.generic+=/death_coil,if=!talent.shadow_infusion.enabled&!talent.dark_arbiter.enabled
actions.aoe=death_and_decay,if=spell_targets.death_and_decay>=2
actions.aoe+=/epidemic,if=spell_targets.epidemic>4
actions.aoe+=/scourge_strike,if=spell_targets.scourge_strike>=2&(dot.death_and_decay.ticking|dot.defile.ticking)
actions.aoe+=/clawing_shadows,if=spell_targets.clawing_shadows>=2&(dot.death_and_decay.ticking|dot.defile.ticking)
actions.aoe+=/epidemic,if=spell_targets.epidemic>2
]]

