local _, internal = ...
internal.apls = internal.apls or {}

internal.apls["legion-dev::Tier19P::Hunter_BM_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=fishbrul_special
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/potion,name=deadly_grace
actions+=/a_murder_of_crows
actions+=/stampede,if=buff.bloodlust.up|buff.bestial_wrath.up|cooldown.bestial_wrath.remains<=2|target.time_to_die<=14
actions+=/dire_beast,if=cooldown.bestial_wrath.remains>2
actions+=/dire_frenzy,if=cooldown.bestial_wrath.remains>2
actions+=/aspect_of_the_wild,if=buff.bestial_wrath.up
actions+=/barrage,if=spell_targets.barrage>1|(spell_targets.barrage=1&focus>90)
actions+=/titans_thunder,if=cooldown.dire_beast.remains>=3|buff.bestial_wrath.up&pet.dire_beast.active
actions+=/bestial_wrath
actions+=/multi_shot,if=spell_targets.multi_shot>4&(pet.buff.beast_cleave.remains<gcd.max|pet.buff.beast_cleave.down)
actions+=/kill_command
actions+=/multi_shot,if=spell_targets.multi_shot>1&(pet.buff.beast_cleave.remains<gcd.max*2|pet.buff.beast_cleave.down)
actions+=/chimaera_shot,if=focus<90
actions+=/cobra_shot,if=talent.killer_cobra.enabled&(cooldown.bestial_wrath.remains>=4&(buff.bestial_wrath.up&cooldown.kill_command.remains>=2)|focus>119)|!talent.killer_cobra.enabled&focus>90
]]

internal.apls["legion-dev::Tier19P::Hunter_MM_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=fishbrul_special
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/windburst
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30&(!talent.sidewinders.enabled|cooldown.sidewinders.charges<2)
actions+=/blood_fury
actions+=/berserking
actions+=/auto_shot
actions+=/variable,name=vulnerable_time,value=debuff.vulnerability.remains
actions+=/call_action_list,name=open,if=time<=15&talent.sidewinders.enabled&active_enemies=1
actions+=/call_action_list,name=cooldowns
actions+=/a_murder_of_crows,if=debuff.hunters_mark.down
actions+=/call_action_list,name=trueshotaoe,if=active_enemies>1&!talent.sidewinders.enabled&buff.trueshot.up
actions+=/barrage,if=debuff.hunters_mark.down
actions+=/black_arrow,if=debuff.hunters_mark.down
actions+=/a_murder_of_crows,if=(target.health.pct>30|target.health.pct<=20)&variable.vulnerable_time>execute_time&debuff.hunters_mark.remains>execute_time&focus+(focus.regen*variable.vulnerable_time)>60&focus+(focus.regen*debuff.hunters_mark.remains)>=60
actions+=/barrage,if=variable.vulnerable_time>execute_time&debuff.hunters_mark.remains>execute_time&focus+(focus.regen*variable.vulnerable_time)>90&focus+(focus.regen*debuff.hunters_mark.remains)>=90
actions+=/black_arrow,if=variable.vulnerable_time>execute_time&debuff.hunters_mark.remains>execute_time&focus+(focus.regen*variable.vulnerable_time)>70&focus+(focus.regen*debuff.hunters_mark.remains)>=70
actions+=/piercing_shot,if=!talent.patient_sniper.enabled&focus>50
actions+=/windburst,if=(!talent.patient_sniper.enabled|talent.sidewinders.enabled)&(debuff.hunters_mark.down|debuff.hunters_mark.remains>execute_time&focus+(focus.regen*debuff.hunters_mark.remains)>50)
actions+=/windburst,if=talent.patient_sniper.enabled&!talent.sidewinders.enabled&((debuff.vulnerability.down|debuff.vulnerability.remains<2)|(debuff.hunters_mark.up&buff.marking_targets.up&debuff.vulnerability.down))
actions+=/call_action_list,name=targetdie,if=target.time_to_die<6&active_enemies=1
actions+=/sidewinders,if=(debuff.hunters_mark.down|(buff.marking_targets.down&buff.trueshot.down))&((buff.trueshot.react&focus<80)|charges_fractional>=1.9)
actions+=/sentinel,if=debuff.hunters_mark.down&(buff.marking_targets.down|buff.trueshot.up)
actions+=/marked_shot,target=2,if=!talent.patient_sniper.enabled&debuff.vulnerability.stack<3
actions+=/arcane_shot,if=!talent.patient_sniper.enabled&spell_targets.barrage=1&debuff.vulnerability.stack<3&((buff.marking_targets.up&debuff.hunters_mark.down)|buff.trueshot.up)
actions+=/multishot,if=!talent.patient_sniper.enabled&spell_targets.barrage>1&debuff.vulnerability.stack<3&((buff.marking_targets.up&debuff.hunters_mark.down)|buff.trueshot.up)
actions+=/arcane_shot,if=talent.steady_focus.enabled&spell_targets.barrage=1&(buff.steady_focus.down|buff.steady_focus.remains<2)
actions+=/multishot,if=talent.steady_focus.enabled&spell_targets.barrage>1&(buff.steady_focus.down|buff.steady_focus.remains<2)
actions+=/explosive_shot
actions+=/marked_shot,if=!talent.patient_sniper.enabled|(talent.barrage.enabled&spell_targets.barrage>2)
actions+=/aimed_shot,if=debuff.hunters_mark.remains>execute_time&variable.vulnerable_time>execute_time&(buff.lock_and_load.up|(focus+debuff.hunters_mark.remains*focus.regen>=80&focus+focus.regen*variable.vulnerable_time>=80))
actions+=/aimed_shot,if=debuff.hunters_mark.down&debuff.vulnerability.remains>execute_time&(talent.sidewinders.enabled|buff.marking_targets.down|(debuff.hunters_mark.remains>execute_time+gcd&focus+5+focus.regen*debuff.hunters_mark.remains>80))
actions+=/marked_shot,if=debuff.hunters_mark.remains<1|variable.vulnerable_time<1|spell_targets.barrage>1|buff.trueshot.up
actions+=/marked_shot,if=buff.marking_targets.up&(!talent.sidewinders.enabled|cooldown.sidewinders.charges_fractional>=1.2)
actions+=/sidewinders,if=buff.marking_targets.up&debuff.hunters_mark.down&(focus<=80|(variable.vulnerable_time<2&cooldown.windburst.remains>3&cooldown.sidewinders.charges_fractional>=1.2))
actions+=/piercing_shot,if=talent.patient_sniper.enabled&focus>80
actions+=/arcane_shot,if=spell_targets.barrage=1&(debuff.hunters_mark.down&buff.marking_targets.react|focus.time_to_max>=2)
actions+=/multishot,if=spell_targets.barrage>1&(debuff.hunters_mark.down&buff.marking_targets.react|focus.time_to_max>=2)
actions+=/aimed_shot,if=debuff.vulnerability.down&focus>80&cooldown.windburst.remains>3
actions+=/multishot,if=spell_targets.barrage>2
actions.cooldowns=potion,name=deadly_grace,if=(buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<31
actions.cooldowns+=//trueshot,if=buff.bloodlust.react|target.time_to_die>=(cooldown+30)|buff.bullseye.react>25|target.time_to_die<16
actions.open=a_murder_of_crows
actions.open+=/trueshot
actions.open+=/sidewinders,if=(buff.marking_targets.down&buff.trueshot.remains<2)|(charges_fractional>=1.9&focus<80)
actions.open+=/marked_shot
actions.open+=/aimed_shot,if=buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.open+=/black_arrow
actions.open+=/barrage
actions.open+=/aimed_shot,if=execute_time<debuff.vulnerability.remains
actions.open+=/sidewinders
actions.open+=/aimed_shot
actions.open+=/arcane_shot
actions.targetdie=marked_shot
actions.targetdie+=/windburst
actions.targetdie+=/aimed_shot,if=execute_time<debuff.vulnerability.remains
actions.targetdie+=/sidewinders
actions.targetdie+=/aimed_shot
actions.targetdie+=/arcane_shot
actions.trueshotaoe=marked_shot
actions.trueshotaoe+=/piercing_shot
actions.trueshotaoe+=/barrage
actions.trueshotaoe+=/explosive_shot
actions.trueshotaoe+=/aimed_shot,if=active_enemies=2&buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.trueshotaoe+=/multishot
]]

internal.apls["legion-dev::Tier19P::Hunter_SV_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=potion_of_the_old_war
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/harpoon
actions=auto_attack
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/use_item,name=tirathons_betrayal
actions+=/potion,name=old_war
actions+=/steel_trap
actions+=/explosive_trap
actions+=/dragonsfire_grenade
actions+=/caltrops
actions+=/carve,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies>=3&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)
actions+=/raptor_strike,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies<=2&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)|talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains<gcd.max|buff.moknathal_tactics.down)
actions+=/aspect_of_the_eagle
actions+=/fury_of_the_eagle,if=buff.mongoose_fury.up&(buff.mongoose_fury.stack=6|action.mongoose_bite.charges=0&cooldown.snake_hunter.remains|buff.mongoose_fury.remains<=gcd.max*2)
actions+=/mongoose_bite,if=buff.aspect_of_the_eagle.up&(charges>=2|charges>=1&cooldown.mongoose_bite.remains<=2)|(buff.mongoose_fury.up|cooldown.fury_of_the_eagle.remains<5|charges=3)
actions+=/a_murder_of_crows
actions+=/lacerate,if=dot.lacerate.ticking&dot.lacerate.remains<=3|target.time_to_die>=5
actions+=/snake_hunter,if=action.mongoose_bite.charges<=1&buff.mongoose_fury.remains>gcd.max*4|action.mongoose_bite.charges=0&buff.aspect_of_the_eagle.up
actions+=/flanking_strike,if=talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains>=3)|!talent.way_of_the_moknathal.enabled
actions+=/butchery,if=spell_targets.butchery>=2
actions+=/carve,if=spell_targets.carve>=4
actions+=/spitting_cobra
actions+=/throwing_axes
actions+=/raptor_strike,if=!talent.throwing_axes.enabled&focus>75-cooldown.flanking_strike.remains*focus.regen
]]

internal.apls["legion-dev::Tier19H::Hunter_BM_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=fishbrul_special
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/potion,name=deadly_grace
actions+=/a_murder_of_crows
actions+=/stampede,if=buff.bloodlust.up|buff.bestial_wrath.up|cooldown.bestial_wrath.remains<=2|target.time_to_die<=14
actions+=/dire_beast,if=cooldown.bestial_wrath.remains>2
actions+=/dire_frenzy,if=cooldown.bestial_wrath.remains>2
actions+=/aspect_of_the_wild,if=buff.bestial_wrath.up
actions+=/barrage,if=spell_targets.barrage>1|(spell_targets.barrage=1&focus>90)
actions+=/titans_thunder,if=cooldown.dire_beast.remains>=3|buff.bestial_wrath.up&pet.dire_beast.active
actions+=/bestial_wrath
actions+=/multi_shot,if=spell_targets.multi_shot>4&(pet.buff.beast_cleave.remains<gcd.max|pet.buff.beast_cleave.down)
actions+=/kill_command
actions+=/multi_shot,if=spell_targets.multi_shot>1&(pet.buff.beast_cleave.remains<gcd.max*2|pet.buff.beast_cleave.down)
actions+=/chimaera_shot,if=focus<90
actions+=/cobra_shot,if=talent.killer_cobra.enabled&(cooldown.bestial_wrath.remains>=4&(buff.bestial_wrath.up&cooldown.kill_command.remains>=2)|focus>119)|!talent.killer_cobra.enabled&focus>90
]]

internal.apls["legion-dev::Tier19H::Hunter_MM_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=fishbrul_special
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/windburst
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30&(!talent.sidewinders.enabled|cooldown.sidewinders.charges<2)
actions+=/blood_fury
actions+=/berserking
actions+=/auto_shot
actions+=/variable,name=vulnerable_time,value=debuff.vulnerability.remains
actions+=/call_action_list,name=open,if=time<=15&talent.sidewinders.enabled&active_enemies=1
actions+=/call_action_list,name=cooldowns
actions+=/a_murder_of_crows,if=debuff.hunters_mark.down
actions+=/call_action_list,name=trueshotaoe,if=active_enemies>1&!talent.sidewinders.enabled&buff.trueshot.up
actions+=/barrage,if=debuff.hunters_mark.down
actions+=/black_arrow,if=debuff.hunters_mark.down
actions+=/a_murder_of_crows,if=(target.health.pct>30|target.health.pct<=20)&variable.vulnerable_time>execute_time&debuff.hunters_mark.remains>execute_time&focus+(focus.regen*variable.vulnerable_time)>60&focus+(focus.regen*debuff.hunters_mark.remains)>=60
actions+=/barrage,if=variable.vulnerable_time>execute_time&debuff.hunters_mark.remains>execute_time&focus+(focus.regen*variable.vulnerable_time)>90&focus+(focus.regen*debuff.hunters_mark.remains)>=90
actions+=/black_arrow,if=variable.vulnerable_time>execute_time&debuff.hunters_mark.remains>execute_time&focus+(focus.regen*variable.vulnerable_time)>70&focus+(focus.regen*debuff.hunters_mark.remains)>=70
actions+=/piercing_shot,if=!talent.patient_sniper.enabled&focus>50
actions+=/windburst,if=(!talent.patient_sniper.enabled|talent.sidewinders.enabled)&(debuff.hunters_mark.down|debuff.hunters_mark.remains>execute_time&focus+(focus.regen*debuff.hunters_mark.remains)>50)
actions+=/windburst,if=talent.patient_sniper.enabled&!talent.sidewinders.enabled&((debuff.vulnerability.down|debuff.vulnerability.remains<2)|(debuff.hunters_mark.up&buff.marking_targets.up&debuff.vulnerability.down))
actions+=/call_action_list,name=targetdie,if=target.time_to_die<6&active_enemies=1
actions+=/sidewinders,if=(debuff.hunters_mark.down|(buff.marking_targets.down&buff.trueshot.down))&((buff.trueshot.react&focus<80)|charges_fractional>=1.9)
actions+=/sentinel,if=debuff.hunters_mark.down&(buff.marking_targets.down|buff.trueshot.up)
actions+=/marked_shot,target=2,if=!talent.patient_sniper.enabled&debuff.vulnerability.stack<3
actions+=/arcane_shot,if=!talent.patient_sniper.enabled&spell_targets.barrage=1&debuff.vulnerability.stack<3&((buff.marking_targets.up&debuff.hunters_mark.down)|buff.trueshot.up)
actions+=/multishot,if=!talent.patient_sniper.enabled&spell_targets.barrage>1&debuff.vulnerability.stack<3&((buff.marking_targets.up&debuff.hunters_mark.down)|buff.trueshot.up)
actions+=/arcane_shot,if=talent.steady_focus.enabled&spell_targets.barrage=1&(buff.steady_focus.down|buff.steady_focus.remains<2)
actions+=/multishot,if=talent.steady_focus.enabled&spell_targets.barrage>1&(buff.steady_focus.down|buff.steady_focus.remains<2)
actions+=/explosive_shot
actions+=/marked_shot,if=!talent.patient_sniper.enabled|(talent.barrage.enabled&spell_targets.barrage>2)
actions+=/aimed_shot,if=debuff.hunters_mark.remains>execute_time&variable.vulnerable_time>execute_time&(buff.lock_and_load.up|(focus+debuff.hunters_mark.remains*focus.regen>=80&focus+focus.regen*variable.vulnerable_time>=80))
actions+=/aimed_shot,if=debuff.hunters_mark.down&debuff.vulnerability.remains>execute_time&(talent.sidewinders.enabled|buff.marking_targets.down|(debuff.hunters_mark.remains>execute_time+gcd&focus+5+focus.regen*debuff.hunters_mark.remains>80))
actions+=/marked_shot,if=debuff.hunters_mark.remains<1|variable.vulnerable_time<1|spell_targets.barrage>1|buff.trueshot.up
actions+=/marked_shot,if=buff.marking_targets.up&(!talent.sidewinders.enabled|cooldown.sidewinders.charges_fractional>=1.2)
actions+=/sidewinders,if=buff.marking_targets.up&debuff.hunters_mark.down&(focus<=80|(variable.vulnerable_time<2&cooldown.windburst.remains>3&cooldown.sidewinders.charges_fractional>=1.2))
actions+=/piercing_shot,if=talent.patient_sniper.enabled&focus>80
actions+=/arcane_shot,if=spell_targets.barrage=1&(debuff.hunters_mark.down&buff.marking_targets.react|focus.time_to_max>=2)
actions+=/multishot,if=spell_targets.barrage>1&(debuff.hunters_mark.down&buff.marking_targets.react|focus.time_to_max>=2)
actions+=/aimed_shot,if=debuff.vulnerability.down&focus>80&cooldown.windburst.remains>3
actions+=/multishot,if=spell_targets.barrage>2
actions.cooldowns=potion,name=deadly_grace,if=(buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<31
actions.cooldowns+=//trueshot,if=buff.bloodlust.react|target.time_to_die>=(cooldown+30)|buff.bullseye.react>25|target.time_to_die<16
actions.open=a_murder_of_crows
actions.open+=/trueshot
actions.open+=/sidewinders,if=(buff.marking_targets.down&buff.trueshot.remains<2)|(charges_fractional>=1.9&focus<80)
actions.open+=/marked_shot
actions.open+=/aimed_shot,if=buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.open+=/black_arrow
actions.open+=/barrage
actions.open+=/aimed_shot,if=execute_time<debuff.vulnerability.remains
actions.open+=/sidewinders
actions.open+=/aimed_shot
actions.open+=/arcane_shot
actions.targetdie=marked_shot
actions.targetdie+=/windburst
actions.targetdie+=/aimed_shot,if=execute_time<debuff.vulnerability.remains
actions.targetdie+=/sidewinders
actions.targetdie+=/aimed_shot
actions.targetdie+=/arcane_shot
actions.trueshotaoe=marked_shot
actions.trueshotaoe+=/piercing_shot
actions.trueshotaoe+=/barrage
actions.trueshotaoe+=/explosive_shot
actions.trueshotaoe+=/aimed_shot,if=active_enemies=2&buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.trueshotaoe+=/multishot
]]

internal.apls["legion-dev::Tier19H::Hunter_SV_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=potion_of_the_old_war
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/harpoon
actions=auto_attack
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/use_item,name=tirathons_betrayal
actions+=/potion,name=old_war
actions+=/steel_trap
actions+=/explosive_trap
actions+=/dragonsfire_grenade
actions+=/caltrops
actions+=/carve,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies>=3&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)
actions+=/raptor_strike,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies<=2&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)|talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains<gcd.max|buff.moknathal_tactics.down)
actions+=/aspect_of_the_eagle
actions+=/fury_of_the_eagle,if=buff.mongoose_fury.up&(buff.mongoose_fury.stack=6|action.mongoose_bite.charges=0&cooldown.snake_hunter.remains|buff.mongoose_fury.remains<=gcd.max*2)
actions+=/mongoose_bite,if=buff.aspect_of_the_eagle.up&(charges>=2|charges>=1&cooldown.mongoose_bite.remains<=2)|(buff.mongoose_fury.up|cooldown.fury_of_the_eagle.remains<5|charges=3)
actions+=/a_murder_of_crows
actions+=/lacerate,if=dot.lacerate.ticking&dot.lacerate.remains<=3|target.time_to_die>=5
actions+=/snake_hunter,if=action.mongoose_bite.charges<=1&buff.mongoose_fury.remains>gcd.max*4|action.mongoose_bite.charges=0&buff.aspect_of_the_eagle.up
actions+=/flanking_strike,if=talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains>=3)|!talent.way_of_the_moknathal.enabled
actions+=/butchery,if=spell_targets.butchery>=2
actions+=/carve,if=spell_targets.carve>=4
actions+=/spitting_cobra
actions+=/throwing_axes
actions+=/raptor_strike,if=!talent.throwing_axes.enabled&focus>75-cooldown.flanking_strike.remains*focus.regen
]]

