local _, internal = ...
internal.apls = internal.apls or {}

internal.apls["legion-dev::Tier19P::Hunter_BM_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/a_murder_of_crows
actions+=/stampede,if=buff.bloodlust.up|buff.bestial_wrath.up|cooldown.bestial_wrath.remains<=2|target.time_to_die<=14
actions+=/dire_beast,if=cooldown.bestial_wrath.remains>2
actions+=/dire_frenzy,if=cooldown.bestial_wrath.remains>2
actions+=/aspect_of_the_wild,if=buff.bestial_wrath.up
actions+=/barrage,if=spell_targets.barrage>1|(spell_targets.barrage=1&focus>90)
actions+=/titans_thunder,if=cooldown.dire_beast.remains>=3|buff.bestial_wrath.up&pet.dire_beast.active
actions+=/bestial_wrath
actions+=/multishot,if=spell_targets.multi_shot>4&(pet.buff.beast_cleave.remains<gcd.max|pet.buff.beast_cleave.down)
actions+=/kill_command
actions+=/multishot,if=spell_targets.multi_shot>1&(pet.buff.beast_cleave.remains<gcd.max*2|pet.buff.beast_cleave.down)
actions+=/chimaera_shot,if=focus<90
actions+=/cobra_shot,if=talent.killer_cobra.enabled&(cooldown.bestial_wrath.remains>=4&(buff.bestial_wrath.up&cooldown.kill_command.remains>=2)|focus>119)|!talent.killer_cobra.enabled&focus>90
]]

internal.apls["legion-dev::Tier19P::Hunter_MM_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/trueshot,if=(target.time_to_die>195|target.health.pct<5)|buff.bullseye.stack>15
actions+=/marked_shot,if=!talent.sidewinders.enabled&prev_gcd.sentinel&debuff.hunters_mark.up
actions+=/call_action_list,name=careful_aim,if=(talent.careful_aim.enabled&target.health.pct>80)&spell_targets.barrage=1
actions+=/a_murder_of_crows
actions+=/barrage
actions+=/piercing_shot,if=!talent.patient_sniper.enabled&focus>50
actions+=/windburst
actions+=/call_action_list,name=patientless,if=!talent.patient_sniper.enabled
actions+=/arcane_shot,if=(talent.steady_focus.enabled&buff.steady_focus.down&focus.time_to_max>=2)|(talent.true_aim.enabled&(debuff.true_aim.stack<1&focus.time_to_max>=2|debuff.true_aim.remains<2))
actions+=/multishot,if=(talent.steady_focus.enabled&buff.steady_focus.down&focus.time_to_max>=2&spell_targets.multishot>1)
actions+=/sidewinders,if=spell_targets.sidewinders>1&(!debuff.hunters_mark.up&(buff.marking_targets.up|buff.trueshot.up|charges=2|focus<80&(charges<=1&recharge_time<=5)))
actions+=/explosive_shot
actions+=/piercing_shot,if=talent.patient_sniper.enabled&focus>80
actions+=/marked_shot,if=talent.sidewinders.enabled&(!talent.patient_sniper.enabled|debuff.vulnerability.remains<2)|!talent.sidewinders.enabled
actions+=/aimed_shot,if=cast_time<debuff.vulnerability.remains&(focus+cast_regen>80|debuff.hunters_mark.down)
actions+=/black_arrow
actions+=/multishot,if=spell_targets.multishot>1&(!debuff.hunters_mark.up&buff.marking_targets.up&cast_regen+action.aimed_shot.cast_regen<=focus.deficit)
actions+=/arcane_shot,if=(!debuff.hunters_mark.up&buff.marking_targets.up)|focus.time_to_max>=2
actions+=/sidewinders,if=!debuff.hunters_mark.up&(buff.marking_targets.up|buff.trueshot.up|charges=2|focus<80&(charges<=1&recharge_time<=5))
actions.patientless=arcane_shot,if=debuff.vulnerability.stack<3&buff.marking_targets.up&debuff.hunters_mark.down&spell_targets.arcane_shot=1
actions.patientless+=/marked_shot,if=debuff.vulnerability.stack<3|debuff.hunters_mark.remains<5|(focus<50|focus>80)
actions.patientless+=/sentinel,if=!talent.sidewinders.enabled&debuff.hunters_mark.down&spell_targets.sentinel>1
actions.patientless+=/explosive_shot
actions.patientless+=/aimed_shot,if=debuff.hunters_mark.down&cast_time<debuff.vulnerability.remains
actions.patientless+=/marked_shot,if=debuff.hunters_mark.remains>5
actions.patientless+=/black_arrow
actions.patientless+=/multishot,if=spell_targets.multishot>1&(cast_regen+action.aimed_shot.cast_regen<=focus.deficit)
actions.patientless+=/arcane_shot,if=cast_regen+action.aimed_shot.cast_regen<=focus.deficit&spell_targets.arcane_shot=1
actions.careful_aim=windburst
actions.careful_aim+=/arcane_shot,if=(talent.steady_focus.enabled&buff.steady_focus.down&spell_targets.arcane_shot=1)|(talent.true_aim.enabled&(debuff.true_aim.stack<1&focus.time_to_max>=2|debuff.true_aim.remains<2))
actions.careful_aim+=/marked_shot,if=talent.sidewinders.enabled&(!talent.patient_sniper.enabled|debuff.vulnerability.remains<2)|!talent.sidewinders.enabled
actions.careful_aim+=/aimed_shot,if=debuff.hunters_mark.down&cast_time<debuff.vulnerability.remains
actions.careful_aim+=/multishot,if=spell_targets.multishot>1&(buff.marking_targets.up|focus.time_to_max>=2)
actions.careful_aim+=/arcane_shot,if=spell_targets.arcane_shot=1&(buff.marking_targets.up|focus.time_to_max>=2)
actions.careful_aim+=/sidewinders,if=!debuff.hunters_mark.up&(buff.marking_targets.up|buff.trueshot.up|charges=2|focus<80&(charges<=1&recharge_time<=5))
]]

internal.apls["legion-dev::Tier19P::Hunter_SV_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/harpoon
actions=auto_attack
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/steel_trap
actions+=/explosive_trap
actions+=/dragonsfire_grenade
actions+=/caltrops
actions+=/carve,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies>=3&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)
actions+=/raptor_strike,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies<=2&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)|talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains<gcd.max|buff.moknathal_tactics.down)
actions+=/aspect_of_the_eagle
actions+=/fury_of_the_eagle,if=buff.mongoose_fury.up&(buff.mongoose_fury.stack=6|action.mongoose_bite.charges=0&cooldown.snake_hunter.remains|buff.mongoose_fury.remains<=gcd.max*2)
actions+=/mongoose_bite,if=buff.aspect_of_the_eagle.up&(charges>=2|charges>=1&cooldown.mongoose_bite.remains<=2)|(buff.mongoose_fury.up|cooldown.fury_of_the_eagle.remains<5|charges=3)
actions+=/a_murder_of_crows
actions+=/lacerate,if=dot.lacerate.ticking&dot.lacerate.remains<=3|target.time_to_die>=5
actions+=/snake_hunter,if=action.mongoose_bite.charges<=1&buff.mongoose_fury.remains>gcd.max*4|action.mongoose_bite.charges=0&buff.aspect_of_the_eagle.up
actions+=/flanking_strike,if=talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains>=3)|!talent.way_of_the_moknathal.enabled
actions+=/butchery,if=spell_targets.butchery>=2
actions+=/carve,if=spell_targets.carve>=4
actions+=/spitting_cobra
actions+=/throwing_axes
actions+=/raptor_strike,if=!talent.throwing_axes.enabled&focus>75-cooldown.flanking_strike.remains*focus.regen
]]

internal.apls["legion-dev::Tier19H::Hunter_BM_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/a_murder_of_crows
actions+=/stampede,if=buff.bloodlust.up|buff.bestial_wrath.up|cooldown.bestial_wrath.remains<=2|target.time_to_die<=14
actions+=/dire_beast,if=cooldown.bestial_wrath.remains>2
actions+=/dire_frenzy,if=cooldown.bestial_wrath.remains>2
actions+=/aspect_of_the_wild,if=buff.bestial_wrath.up
actions+=/barrage,if=spell_targets.barrage>1|(spell_targets.barrage=1&focus>90)
actions+=/titans_thunder,if=cooldown.dire_beast.remains>=3|buff.bestial_wrath.up&pet.dire_beast.active
actions+=/bestial_wrath
actions+=/multishot,if=spell_targets.multi_shot>4&(pet.buff.beast_cleave.remains<gcd.max|pet.buff.beast_cleave.down)
actions+=/kill_command
actions+=/multishot,if=spell_targets.multi_shot>1&(pet.buff.beast_cleave.remains<gcd.max*2|pet.buff.beast_cleave.down)
actions+=/chimaera_shot,if=focus<90
actions+=/cobra_shot,if=talent.killer_cobra.enabled&(cooldown.bestial_wrath.remains>=4&(buff.bestial_wrath.up&cooldown.kill_command.remains>=2)|focus>119)|!talent.killer_cobra.enabled&focus>90
]]

internal.apls["legion-dev::Tier19H::Hunter_MM_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/trueshot,if=(target.time_to_die>175|target.health.pct<5)|buff.bullseye.stack>15
actions+=/marked_shot,if=!talent.sidewinders.enabled&prev_gcd.sentinel&debuff.hunters_mark.up
actions+=/call_action_list,name=careful_aim,if=(talent.careful_aim.enabled&target.health.pct>80)&spell_targets.barrage=1
actions+=/a_murder_of_crows
actions+=/barrage
actions+=/piercing_shot,if=!talent.patient_sniper.enabled&focus>50
actions+=/windburst
actions+=/call_action_list,name=patientless,if=!talent.patient_sniper.enabled
actions+=/arcane_shot,if=(talent.steady_focus.enabled&buff.steady_focus.down&focus.time_to_max>=2)|(talent.true_aim.enabled&(debuff.true_aim.stack<1&focus.time_to_max>=2|debuff.true_aim.remains<2))
actions+=/multishot,if=(talent.steady_focus.enabled&buff.steady_focus.down&focus.time_to_max>=2&spell_targets.multishot>1)
actions+=/sidewinders,if=spell_targets.sidewinders>1&(!debuff.hunters_mark.up&(buff.marking_targets.up|buff.trueshot.up|charges=2|focus<80&(charges<=1&recharge_time<=5)))
actions+=/explosive_shot
actions+=/piercing_shot,if=talent.patient_sniper.enabled&focus>80
actions+=/marked_shot,if=talent.sidewinders.enabled&(!talent.patient_sniper.enabled|debuff.vulnerability.remains<2)|!talent.sidewinders.enabled
actions+=/aimed_shot,if=cast_time<debuff.vulnerability.remains&(focus+cast_regen>80|debuff.hunters_mark.down)
actions+=/black_arrow
actions+=/multishot,if=spell_targets.multishot>1&(!debuff.hunters_mark.up&buff.marking_targets.up&cast_regen+action.aimed_shot.cast_regen<=focus.deficit)
actions+=/arcane_shot,if=(!debuff.hunters_mark.up&buff.marking_targets.up)|focus.time_to_max>=2
actions+=/sidewinders,if=!debuff.hunters_mark.up&(buff.marking_targets.up|buff.trueshot.up|charges=2|focus<80&(charges<=1&recharge_time<=5))
actions.patientless=arcane_shot,if=debuff.vulnerability.stack<3&buff.marking_targets.up&debuff.hunters_mark.down&spell_targets.arcane_shot=1
actions.patientless+=/marked_shot,if=debuff.vulnerability.stack<3|debuff.hunters_mark.remains<5|(focus<50|focus>80)
actions.patientless+=/sentinel,if=!talent.sidewinders.enabled&debuff.hunters_mark.down&spell_targets.sentinel>1
actions.patientless+=/explosive_shot
actions.patientless+=/aimed_shot,if=debuff.hunters_mark.down&cast_time<debuff.vulnerability.remains
actions.patientless+=/marked_shot,if=debuff.hunters_mark.remains>5
actions.patientless+=/black_arrow
actions.patientless+=/multishot,if=spell_targets.multishot>1&(cast_regen+action.aimed_shot.cast_regen<=focus.deficit)
actions.patientless+=/arcane_shot,if=cast_regen+action.aimed_shot.cast_regen<=focus.deficit&spell_targets.arcane_shot=1
actions.careful_aim=windburst
actions.careful_aim+=/arcane_shot,if=(talent.steady_focus.enabled&buff.steady_focus.down&spell_targets.arcane_shot=1)|(talent.true_aim.enabled&(debuff.true_aim.stack<1&focus.time_to_max>=2|debuff.true_aim.remains<2))
actions.careful_aim+=/marked_shot,if=talent.sidewinders.enabled&(!talent.patient_sniper.enabled|debuff.vulnerability.remains<2)|!talent.sidewinders.enabled
actions.careful_aim+=/aimed_shot,if=debuff.hunters_mark.down&cast_time<debuff.vulnerability.remains
actions.careful_aim+=/multishot,if=spell_targets.multishot>1&(buff.marking_targets.up|focus.time_to_max>=2)
actions.careful_aim+=/arcane_shot,if=spell_targets.arcane_shot=1&(buff.marking_targets.up|focus.time_to_max>=2)
actions.careful_aim+=/sidewinders,if=!debuff.hunters_mark.up&(buff.marking_targets.up|buff.trueshot.up|charges=2|focus<80&(charges<=1&recharge_time<=5))
]]

internal.apls["legion-dev::Tier19H::Hunter_SV_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/summon_pet
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/harpoon
actions=auto_attack
actions+=/arcane_torrent,if=focus.deficit>=30
actions+=/blood_fury
actions+=/berserking
actions+=/steel_trap
actions+=/explosive_trap
actions+=/dragonsfire_grenade
actions+=/caltrops
actions+=/carve,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies>=3&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)
actions+=/raptor_strike,cycle_targets=1,if=talent.serpent_sting.enabled&active_enemies<=2&(!dot.serpent_sting.ticking|dot.serpent_sting.remains<=gcd.max)|talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains<gcd.max|buff.moknathal_tactics.down)
actions+=/aspect_of_the_eagle
actions+=/fury_of_the_eagle,if=buff.mongoose_fury.up&(buff.mongoose_fury.stack=6|action.mongoose_bite.charges=0&cooldown.snake_hunter.remains|buff.mongoose_fury.remains<=gcd.max*2)
actions+=/mongoose_bite,if=buff.aspect_of_the_eagle.up&(charges>=2|charges>=1&cooldown.mongoose_bite.remains<=2)|(buff.mongoose_fury.up|cooldown.fury_of_the_eagle.remains<5|charges=3)
actions+=/a_murder_of_crows
actions+=/lacerate,if=dot.lacerate.ticking&dot.lacerate.remains<=3|target.time_to_die>=5
actions+=/snake_hunter,if=action.mongoose_bite.charges<=1&buff.mongoose_fury.remains>gcd.max*4|action.mongoose_bite.charges=0&buff.aspect_of_the_eagle.up
actions+=/flanking_strike,if=talent.way_of_the_moknathal.enabled&(buff.moknathal_tactics.remains>=3)|!talent.way_of_the_moknathal.enabled
actions+=/butchery,if=spell_targets.butchery>=2
actions+=/carve,if=spell_targets.carve>=4
actions+=/spitting_cobra
actions+=/throwing_axes
actions+=/raptor_strike,if=!talent.throwing_axes.enabled&focus>75-cooldown.flanking_strike.remains*focus.regen
]]

internal.apls["legion-dev::legion::Hunter_BM_Legion"] = [[
actions.precombat+=/summon_pet
actions=auto_shot
actions+=/aspect_of_the_wild
actions+=/stampede
actions+=/titans_thunder,if=buff.dire_beast.remains>6
actions+=/bestial_wrath
actions+=/kill_command
actions+=/chimaera_shot
actions+=/dire_beast
actions+=/dire_frenzy
actions+=/barrage
actions+=/cobra_shot,if=focus>90
]]

internal.apls["legion-dev::legion::Hunter_MM_Legion"] = [[
actions.precombat+=/summon_pet
actions.precombat+=/volley
actions=auto_shot
actions+=/trueshot,if=!artifact.bullseye.enabled|target.time_to_die>cooldown.trueshot.duration+15|target.time_to_die<18|buff.bullseye.stack>15
actions+=/a_murder_of_crows
actions+=/barrage
actions+=/piercing_shot
actions+=/explosive_shot
actions+=/black_arrow
actions+=/windburst
actions+=/marked_shot,if=!talent.patient_sniper.enabled|debuff.vulnerability.remains<2
actions+=/aimed_shot,if=cast_time<debuff.vulnerability.remains&(focus+cast_regen>80|!debuff.hunters_mark.up)
actions+=/multishot,if=spell_targets.multishot>1
actions+=/arcane_shot
actions+=/sidewinders,if=!debuff.hunters_mark.up&(buff.marking_targets.up|buff.trueshot.up|charges=2)
actions+=/aimed_shot,if=focus+cast_regen>80
]]

internal.apls["legion-dev::legion::Hunter_SV_Legion"] = [[
actions.precombat+=/summon_pet
actions=auto_attack
actions+=/aspect_of_the_eagle
actions+=/spitting_cobra
actions+=/raptor_strike,if=buff.moknathal_tactics.remains<2
actions+=/dragonsfire_grenade
actions+=/mongoose_bite,if=charges=3|(cooldown.fury_of_the_eagle.remains<5&buff.mongoose_fury.up)
actions+=/call_action_list,name=moknathal,if=talent.way_of_the_moknathal.enabled
actions+=/explosive_trap
actions+=/lacerate
actions+=/flanking_strike
actions+=/fury_of_the_eagle,if=buff.mongoose_fury.stack>=3
actions+=/raptor_strike,if=buff.moknathal_tactics.remains<2
actions+=/a_murder_of_crows
actions+=/snake_hunter,if=action.mongoose_bite.charges=0
actions+=/mongoose_bite,if=(charges=3|buff.mongoose_fury.up)
actions+=/throwing_axes
actions.moknathal=mongoose_bite,if=(charges=3|buff.mongoose_fury.up)
actions.moknathal+=/explosive_trap
actions.moknathal+=/lacerate
actions.moknathal+=/flanking_strike,if=focus>=90
actions+=/flanking_strike,if=focus>90
]]

