local _, internal = ...
internal.apls = internal.apls or {}

internal.apls["legion-dev::Tier19P::Rogue_Assassination_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/apply_poison
actions.precombat+=/stealth
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/marked_for_death
actions=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=25|debuff.vendetta.up
actions+=/use_item,slot=trinket2,if=buff.bloodlust.react|target.time_to_die<=20|debuff.vendetta.up
actions+=/blood_fury,if=debuff.vendetta.up
actions+=/berserking,if=debuff.vendetta.up
actions+=/arcane_torrent,if=debuff.vendetta.up&energy.deficit>50
actions+=/call_action_list,name=cds
actions+=/rupture,if=combo_points>=2&!ticking&time<10&!artifact.urge_to_kill.enabled
actions+=/rupture,if=combo_points>=4&!ticking
actions+=/pool_resource,for_next=1
actions+=/kingsbane,if=!talent.exsanguinate.enabled&(buff.vendetta.up|cooldown.vendetta.remains>10)|talent.exsanguinate.enabled&dot.rupture.exsanguinated
actions+=/run_action_list,name=exsang_combo,if=cooldown.exsanguinate.remains<3&talent.exsanguinate.enabled&(buff.vendetta.up|cooldown.vendetta.remains>15)
actions+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=8
actions+=/call_action_list,name=exsang,if=dot.rupture.exsanguinated
actions+=/rupture,if=talent.exsanguinate.enabled&remains-cooldown.exsanguinate.remains<(4+cp_max_spend*4)*0.3&new_duration-cooldown.exsanguinate.remains>=(4+cp_max_spend*4)*0.3+3
actions+=/call_action_list,name=finish
actions+=/call_action_list,name=build
actions.cds=marked_for_death,target_if=min:target.time_to_die,if=combo_points.deficit>=5
actions.cds+=/vendetta,if=target.time_to_die<20
actions.cds+=/vendetta,if=artifact.urge_to_kill.enabled&dot.rupture.ticking&(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains<5)&(energy<55|time<10|spell_targets.fan_of_knives>=2)
actions.cds+=/vendetta,if=!artifact.urge_to_kill.enabled&dot.rupture.ticking&(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains<1)
actions.cds+=/vanish,if=talent.subterfuge.enabled&combo_points<=2&!dot.rupture.exsanguinated|talent.shadow_focus.enabled&!dot.rupture.exsanguinated&combo_points.deficit>=2
actions.exsang_combo=vanish,if=talent.nightstalker.enabled&combo_points>=cp_max_spend&cooldown.exsanguinate.remains<1&gcd.remains=0&energy>=25
actions.exsang_combo+=/rupture,if=combo_points>=cp_max_spend&(!talent.nightstalker.enabled|buff.vanish.up|cooldown.vanish.remains>15)&cooldown.exsanguinate.remains<1
actions.exsang_combo+=/exsanguinate,if=prev_gcd.rupture&dot.rupture.remains>22+4*talent.deeper_stratagem.enabled&cooldown.vanish.remains>10
actions.exsang_combo+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=8
actions.exsang_combo+=/hemorrhage,if=spell_targets.fan_of_knives>=2&!ticking
actions.exsang_combo+=/call_action_list,name=build
actions.garrote=pool_resource,for_next=1
actions.garrote+=/garrote,cycle_targets=1,if=talent.subterfuge.enabled&!ticking&combo_points.deficit>=1&spell_targets.fan_of_knives>=2
actions.garrote+=/pool_resource,for_next=1
actions.garrote+=/garrote,if=combo_points.deficit>=1&!exsanguinated
actions.exsang=rupture,cycle_targets=1,if=!ticking&combo_points>=cp_max_spend-1&spell_targets.fan_of_knives>1&target.time_to_die-remains>6
actions.exsang+=/rupture,if=combo_points>=cp_max_spend&ticks_remain<2
actions.exsang+=/death_from_above,if=combo_points>=cp_max_spend-1&(dot.rupture.remains>3|dot.rupture.remains>2&spell_targets.fan_of_knives>=3)&spell_targets.fan_of_knives<=6+2*debuff.vendetta.up
actions.exsang+=/envenom,if=combo_points>=cp_max_spend-1&(dot.rupture.remains>3|dot.rupture.remains>2&spell_targets.fan_of_knives>=3)&spell_targets.fan_of_knives<=6+2*debuff.vendetta.up
actions.finish=rupture,cycle_targets=1,if=!ticking&combo_points>=cp_max_spend-1&spell_targets.fan_of_knives>1&target.time_to_die-remains>6
actions.finish+=/rupture,if=combo_points>=cp_max_spend-1&refreshable&!exsanguinated
actions.finish+=/death_from_above,if=combo_points>=cp_max_spend-1&spell_targets.fan_of_knives<=7
actions.finish+=/envenom,if=combo_points>=cp_max_spend-1&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&energy.deficit<40&spell_targets.fan_of_knives<=6
actions.finish+=/envenom,if=combo_points>=cp_max_spend&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&cooldown.garrote.remains<1&spell_targets.fan_of_knives<=6
actions.build=hemorrhage,cycle_targets=1,if=combo_points.deficit>=1&refreshable&dot.rupture.remains>6&spell_targets.fan_of_knives>1&spell_targets.fan_of_knives<=4
actions.build+=/fan_of_knives,if=(spell_targets>=2+debuff.vendetta.up&(combo_points.deficit>=1|energy.deficit<=30))|spell_targets>=7+2*debuff.vendetta.up
actions.build+=/fan_of_knives,if=equipped.the_dreadlords_deceit&((buff.the_dreadlords_deceit.stack>=29|buff.the_dreadlords_deceit.stack>=15&debuff.vendetta.remains<=3)&debuff.vendetta.up|buff.the_dreadlords_deceit.stack>=5&cooldown.vendetta.remains>60&cooldown.vendetta.remains<65)
actions.build+=/hemorrhage,if=(combo_points.deficit>=1&refreshable)|(combo_points.deficit=1&(dot.rupture.exsanguinated&dot.rupture.remains<=2|cooldown.exsanguinate.remains<=2))
actions.build+=/mutilate,if=combo_points.deficit<=1&energy.deficit<=30
actions.build+=/mutilate,if=combo_points.deficit>=2&cooldown.garrote.remains>2
]]

internal.apls["legion-dev::Tier19P::Rogue_Outlaw_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/marked_for_death
actions=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=25|buff.adrenaline_rush.up
actions+=/cancel_buff,name=blade_flurry,if=equipped.shivarran_symmetry&cooldown.blade_flurry.up&buff.blade_flurry.up&spell_targets.blade_flurry>=2|spell_targets.blade_flurry<2&buff.blade_flurry.up
actions+=/blade_flurry,if=spell_targets.blade_flurry>=2&!buff.blade_flurry.up
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent,if=energy.deficit>40
actions+=/adrenaline_rush,if=!buff.adrenaline_rush.up
actions+=/sprint,if=equipped.thraxis_tricksy_treads&combo_points>=action.run_through.cp_max_spend-1-(buff.broadsides.up&buff.jolly_roger.up)+cooldown.death_from_above.up
actions+=/ambush
actions+=/vanish,if=combo_points.deficit>=2+2*(talent.ghostly_strike.enabled&!debuff.ghostly_strike.up)+buff.broadsides.up&energy>60&!buff.jolly_roger.up&artifact.hidden_blade.enabled&!buff.curse_of_the_dreadblades.up
actions+=/shadowmeld,if=combo_points.deficit>=2+2*(talent.ghostly_strike.enabled&!debuff.ghostly_strike.up)+buff.broadsides.up&energy>60&!buff.jolly_roger.up&artifact.hidden_blade.enabled&!buff.curse_of_the_dreadblades.up
actions+=/death_from_above,if=energy.time_to_max>2&combo_points>=action.run_through.cp_max_spend-(buff.broadsides.up&buff.jolly_roger.up)
actions+=/slice_and_dice,if=combo_points>=5&buff.slice_and_dice.remains<target.time_to_die&buff.slice_and_dice.remains<(1+combo_points)*1.8
actions+=/roll_the_bones,if=combo_points>=5&buff.roll_the_bones.remains<target.time_to_die&(buff.roll_the_bones.remains<=3|rtb_buffs<=1)
actions+=/killing_spree,if=energy.time_to_max>5|energy<15
actions+=/cannonball_barrage,if=spell_targets.cannonball_barrage>=1
actions+=/curse_of_the_dreadblades,if=combo_points.deficit>=4
actions+=/marked_for_death,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled+talent.anticipation.enabled
actions+=/call_action_list,name=finish,if=combo_points>=action.run_through.cp_max_spend-1-(buff.broadsides.up&buff.jolly_roger.up)+cooldown.death_from_above.up
actions+=/call_action_list,name=build,if=combo_points<action.run_through.cp_max_spend-1-(buff.broadsides.up&buff.jolly_roger.up)+cooldown.death_from_above.up
actions.finish=between_the_eyes,if=equipped.greenskins_waterlogged_wristcuffs&buff.shark_infested_waters.up
actions.finish+=/run_through,if=!talent.death_from_above.enabled|energy.time_to_max<cooldown.death_from_above.remains+3.5
actions.build=ghostly_strike,if=talent.ghostly_strike.enabled&debuff.ghostly_strike.remains<4.5
actions.build+=/pistol_shot,if=buff.opportunity.up&energy.time_to_max>2
actions.build+=/saber_slash
]]

internal.apls["legion-dev::Tier19P::Rogue_Subtlety_T19P"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/marked_for_death
actions.precombat+=/symbols_of_death
actions=call_action_list,name=cds
actions+=/run_action_list,name=stealthed,if=stealthed|buff.shadowmeld.up
actions+=/call_action_list,name=finish,if=combo_points>=5
actions+=/call_action_list,name=stealth_cds,if=combo_points.deficit>=2+talent.premeditation.enabled&(energy.deficit<=20|(energy.deficit<=45&talent.master_of_shadows.enabled)|(cooldown.shadowmeld.up&!cooldown.vanish.up&cooldown.shadow_dance.charges<=1))
actions+=/call_action_list,name=build,if=energy.deficit<=20|(energy.deficit<=45&talent.master_of_shadows.enabled)
actions.cds=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=25|buff.shadow_blades.up
actions.cds+=/blood_fury,if=stealthed
actions.cds+=/berserking,if=stealthed
actions.cds+=/arcane_torrent,if=stealthed&energy.deficit>70
actions.cds+=/shadow_blades,if=!buff.shadow_blades.up
actions.cds+=/goremaws_bite,if=(combo_points.deficit>=2&energy.deficit>55&time<10)|(combo_points.deficit>=4&energy.deficit>45)|target.time_to_die<8
actions.cds+=/marked_for_death,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled+talent.anticipation.enabled
actions.stealthed=symbols_of_death,if=buff.symbols_of_death.remains<target.time_to_die-4&buff.symbols_of_death.remains<=buff.symbols_of_death.duration*0.3&buff.shadowmeld.down
actions.stealthed+=/call_action_list,name=finish,if=combo_points>=5
actions.stealthed+=/shuriken_storm,if=(combo_points.deficit>=3&spell_targets.shuriken_storm>=3)|buff.the_dreadlords_deceit.stack>=29
actions.stealthed+=/shadowstrike
actions.stealth_cds=shadow_dance,if=charges>=3
actions.stealth_cds+=/vanish
actions.stealth_cds+=/shadow_dance,if=charges>=2
actions.stealth_cds+=/pool_resource,for_next=1,extra_amount=40
actions.stealth_cds+=/shadowmeld,if=energy>=40
actions.stealth_cds+=/shadow_dance
actions.finish=enveloping_shadows,if=buff.enveloping_shadows.remains<target.time_to_die&buff.enveloping_shadows.remains<=combo_points*1.8
actions.finish+=/death_from_above,if=spell_targets.death_from_above>=10
actions.finish+=/nightblade,target_if=max:target.time_to_die,if=target.time_to_die>10&refreshable
actions.finish+=/death_from_above
actions.finish+=/eviscerate
actions.build=shuriken_storm,if=spell_targets.shuriken_storm>=2
actions.build+=/gloomblade
actions.build+=/backstab
]]

internal.apls["legion-dev::Tier19H::Rogue_Assassination_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/apply_poison
actions.precombat+=/stealth
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/marked_for_death
actions=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=25|debuff.vendetta.up
actions+=/blood_fury,if=debuff.vendetta.up
actions+=/berserking,if=debuff.vendetta.up
actions+=/arcane_torrent,if=debuff.vendetta.up&energy.deficit>50
actions+=/call_action_list,name=cds
actions+=/rupture,if=combo_points>=2&!ticking&time<10&!artifact.urge_to_kill.enabled
actions+=/rupture,if=combo_points>=4&!ticking
actions+=/pool_resource,for_next=1
actions+=/kingsbane,if=!talent.exsanguinate.enabled&(buff.vendetta.up|cooldown.vendetta.remains>10)|talent.exsanguinate.enabled&dot.rupture.exsanguinated
actions+=/run_action_list,name=exsang_combo,if=cooldown.exsanguinate.remains<3&talent.exsanguinate.enabled&(buff.vendetta.up|cooldown.vendetta.remains>15)
actions+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=8
actions+=/call_action_list,name=exsang,if=dot.rupture.exsanguinated
actions+=/rupture,if=talent.exsanguinate.enabled&remains-cooldown.exsanguinate.remains<(4+cp_max_spend*4)*0.3&new_duration-cooldown.exsanguinate.remains>=(4+cp_max_spend*4)*0.3+3
actions+=/call_action_list,name=finish
actions+=/call_action_list,name=build
actions.cds=marked_for_death,target_if=min:target.time_to_die,if=combo_points.deficit>=5
actions.cds+=/vendetta,if=target.time_to_die<20
actions.cds+=/vendetta,if=artifact.urge_to_kill.enabled&dot.rupture.ticking&(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains<5)&(energy<55|time<10|spell_targets.fan_of_knives>=2)
actions.cds+=/vendetta,if=!artifact.urge_to_kill.enabled&dot.rupture.ticking&(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains<1)
actions.cds+=/vanish,if=talent.subterfuge.enabled&combo_points<=2&!dot.rupture.exsanguinated|talent.shadow_focus.enabled&!dot.rupture.exsanguinated&combo_points.deficit>=2
actions.exsang_combo=vanish,if=talent.nightstalker.enabled&combo_points>=cp_max_spend&cooldown.exsanguinate.remains<1&gcd.remains=0&energy>=25
actions.exsang_combo+=/rupture,if=combo_points>=cp_max_spend&(!talent.nightstalker.enabled|buff.vanish.up|cooldown.vanish.remains>15)&cooldown.exsanguinate.remains<1
actions.exsang_combo+=/exsanguinate,if=prev_gcd.rupture&dot.rupture.remains>22+4*talent.deeper_stratagem.enabled&cooldown.vanish.remains>10
actions.exsang_combo+=/call_action_list,name=garrote,if=spell_targets.fan_of_knives<=8
actions.exsang_combo+=/hemorrhage,if=spell_targets.fan_of_knives>=2&!ticking
actions.exsang_combo+=/call_action_list,name=build
actions.garrote=pool_resource,for_next=1
actions.garrote+=/garrote,cycle_targets=1,if=talent.subterfuge.enabled&!ticking&combo_points.deficit>=1&spell_targets.fan_of_knives>=2
actions.garrote+=/pool_resource,for_next=1
actions.garrote+=/garrote,if=combo_points.deficit>=1&!exsanguinated
actions.exsang=rupture,cycle_targets=1,if=!ticking&combo_points>=cp_max_spend-1&spell_targets.fan_of_knives>1&target.time_to_die-remains>6
actions.exsang+=/rupture,if=combo_points>=cp_max_spend&ticks_remain<2
actions.exsang+=/death_from_above,if=combo_points>=cp_max_spend-1&(dot.rupture.remains>3|dot.rupture.remains>2&spell_targets.fan_of_knives>=3)&spell_targets.fan_of_knives<=6+2*debuff.vendetta.up
actions.exsang+=/envenom,if=combo_points>=cp_max_spend-1&(dot.rupture.remains>3|dot.rupture.remains>2&spell_targets.fan_of_knives>=3)&spell_targets.fan_of_knives<=6+2*debuff.vendetta.up
actions.finish=rupture,cycle_targets=1,if=!ticking&combo_points>=cp_max_spend-1&spell_targets.fan_of_knives>1&target.time_to_die-remains>6
actions.finish+=/rupture,if=combo_points>=cp_max_spend-1&refreshable&!exsanguinated
actions.finish+=/death_from_above,if=combo_points>=cp_max_spend-1&spell_targets.fan_of_knives<=7
actions.finish+=/envenom,if=combo_points>=cp_max_spend-1&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&energy.deficit<40&spell_targets.fan_of_knives<=6
actions.finish+=/envenom,if=combo_points>=cp_max_spend&!dot.rupture.refreshable&buff.elaborate_planning.remains<2&cooldown.garrote.remains<1&spell_targets.fan_of_knives<=6
actions.build=hemorrhage,cycle_targets=1,if=combo_points.deficit>=1&refreshable&dot.rupture.remains>6&spell_targets.fan_of_knives>1&spell_targets.fan_of_knives<=4
actions.build+=/fan_of_knives,if=(spell_targets>=2+debuff.vendetta.up&(combo_points.deficit>=1|energy.deficit<=30))|spell_targets>=7+2*debuff.vendetta.up
actions.build+=/fan_of_knives,if=equipped.the_dreadlords_deceit&((buff.the_dreadlords_deceit.stack>=29|buff.the_dreadlords_deceit.stack>=15&debuff.vendetta.remains<=3)&debuff.vendetta.up|buff.the_dreadlords_deceit.stack>=5&cooldown.vendetta.remains>60&cooldown.vendetta.remains<65)
actions.build+=/hemorrhage,if=(combo_points.deficit>=1&refreshable)|(combo_points.deficit=1&(dot.rupture.exsanguinated&dot.rupture.remains<=2|cooldown.exsanguinate.remains<=2))
actions.build+=/mutilate,if=combo_points.deficit<=1&energy.deficit<=30
actions.build+=/mutilate,if=combo_points.deficit>=2&cooldown.garrote.remains>2
]]

internal.apls["legion-dev::Tier19H::Rogue_Outlaw_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/marked_for_death
actions=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=25|buff.adrenaline_rush.up
actions+=/cancel_buff,name=blade_flurry,if=equipped.shivarran_symmetry&cooldown.blade_flurry.up&buff.blade_flurry.up&spell_targets.blade_flurry>=2|spell_targets.blade_flurry<2&buff.blade_flurry.up
actions+=/blade_flurry,if=spell_targets.blade_flurry>=2&!buff.blade_flurry.up
actions+=/blood_fury
actions+=/berserking
actions+=/arcane_torrent,if=energy.deficit>40
actions+=/adrenaline_rush,if=!buff.adrenaline_rush.up
actions+=/sprint,if=equipped.thraxis_tricksy_treads&combo_points>=action.run_through.cp_max_spend-1-(buff.broadsides.up&buff.jolly_roger.up)+cooldown.death_from_above.up
actions+=/ambush
actions+=/vanish,if=combo_points.deficit>=2+2*(talent.ghostly_strike.enabled&!debuff.ghostly_strike.up)+buff.broadsides.up&energy>60&!buff.jolly_roger.up&artifact.hidden_blade.enabled&!buff.curse_of_the_dreadblades.up
actions+=/shadowmeld,if=combo_points.deficit>=2+2*(talent.ghostly_strike.enabled&!debuff.ghostly_strike.up)+buff.broadsides.up&energy>60&!buff.jolly_roger.up&artifact.hidden_blade.enabled&!buff.curse_of_the_dreadblades.up
actions+=/death_from_above,if=energy.time_to_max>2&combo_points>=action.run_through.cp_max_spend-(buff.broadsides.up&buff.jolly_roger.up)
actions+=/slice_and_dice,if=combo_points>=5&buff.slice_and_dice.remains<target.time_to_die&buff.slice_and_dice.remains<(1+combo_points)*1.8
actions+=/roll_the_bones,if=combo_points>=5&buff.roll_the_bones.remains<target.time_to_die&(buff.roll_the_bones.remains<=3|rtb_buffs<=1)
actions+=/killing_spree,if=energy.time_to_max>5|energy<15
actions+=/cannonball_barrage,if=spell_targets.cannonball_barrage>=1
actions+=/curse_of_the_dreadblades,if=combo_points.deficit>=4
actions+=/marked_for_death,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled+talent.anticipation.enabled
actions+=/call_action_list,name=finish,if=combo_points>=action.run_through.cp_max_spend-1-(buff.broadsides.up&buff.jolly_roger.up)+cooldown.death_from_above.up
actions+=/call_action_list,name=build,if=combo_points<action.run_through.cp_max_spend-1-(buff.broadsides.up&buff.jolly_roger.up)+cooldown.death_from_above.up
actions.finish=between_the_eyes,if=equipped.greenskins_waterlogged_wristcuffs&buff.shark_infested_waters.up
actions.finish+=/run_through,if=!talent.death_from_above.enabled|energy.time_to_max<cooldown.death_from_above.remains+3.5
actions.build=ghostly_strike,if=talent.ghostly_strike.enabled&debuff.ghostly_strike.remains<4.5
actions.build+=/pistol_shot,if=buff.opportunity.up&energy.time_to_max>2
actions.build+=/saber_slash
]]

internal.apls["legion-dev::Tier19H::Rogue_Subtlety_T19H"] = [[
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/food,type=seedbattered_fish_plate
actions.precombat+=/snapshot_stats
actions.precombat+=/stealth
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/marked_for_death
actions.precombat+=/symbols_of_death
actions=call_action_list,name=cds
actions+=/run_action_list,name=stealthed,if=stealthed|buff.shadowmeld.up
actions+=/call_action_list,name=finish,if=combo_points>=5
actions+=/call_action_list,name=stealth_cds,if=combo_points.deficit>=2+talent.premeditation.enabled&(energy.deficit<=20|(energy.deficit<=45&talent.master_of_shadows.enabled)|(cooldown.shadowmeld.up&!cooldown.vanish.up&cooldown.shadow_dance.charges<=1))
actions+=/call_action_list,name=build,if=energy.deficit<=20|(energy.deficit<=45&talent.master_of_shadows.enabled)
actions.cds=potion,name=deadly_grace,if=buff.bloodlust.react|target.time_to_die<=25|buff.shadow_blades.up
actions.cds+=/blood_fury,if=stealthed
actions.cds+=/berserking,if=stealthed
actions.cds+=/arcane_torrent,if=stealthed&energy.deficit>70
actions.cds+=/shadow_blades,if=!buff.shadow_blades.up
actions.cds+=/goremaws_bite,if=(combo_points.deficit>=2&energy.deficit>55&time<10)|(combo_points.deficit>=4&energy.deficit>45)|target.time_to_die<8
actions.cds+=/marked_for_death,target_if=min:target.time_to_die,if=combo_points.deficit>=4+talent.deeper_strategem.enabled+talent.anticipation.enabled
actions.stealthed=symbols_of_death,if=buff.symbols_of_death.remains<target.time_to_die-4&buff.symbols_of_death.remains<=buff.symbols_of_death.duration*0.3&buff.shadowmeld.down
actions.stealthed+=/call_action_list,name=finish,if=combo_points>=5
actions.stealthed+=/shuriken_storm,if=(combo_points.deficit>=3&spell_targets.shuriken_storm>=3)|buff.the_dreadlords_deceit.stack>=29
actions.stealthed+=/shadowstrike
actions.stealth_cds=shadow_dance,if=charges>=3
actions.stealth_cds+=/vanish
actions.stealth_cds+=/shadow_dance,if=charges>=2
actions.stealth_cds+=/pool_resource,for_next=1,extra_amount=40
actions.stealth_cds+=/shadowmeld,if=energy>=40
actions.stealth_cds+=/shadow_dance
actions.finish=enveloping_shadows,if=buff.enveloping_shadows.remains<target.time_to_die&buff.enveloping_shadows.remains<=combo_points*1.8
actions.finish+=/death_from_above,if=spell_targets.death_from_above>=10
actions.finish+=/nightblade,target_if=max:target.time_to_die,if=target.time_to_die>10&refreshable
actions.finish+=/death_from_above
actions.finish+=/eviscerate
actions.build=shuriken_storm,if=spell_targets.shuriken_storm>=2
actions.build+=/gloomblade
actions.build+=/backstab
]]

