local TJ = LibStub('AceAddon-3.0'):GetAddon('ThousandJabs8')
local Core = TJ:GetModule('Core')
TJ.Generated = TJ.Generated or {}
TJ.Generated.EquippedMapping = TJ.Generated.EquippedMapping or {}

TJ.Generated.EquippedMapping.ailuro_pouncers = { 137024, }
TJ.Generated.EquippedMapping.cold_heart = { 151796, }
TJ.Generated.EquippedMapping.drinking_horn_cover = { 137097, }
TJ.Generated.EquippedMapping.fury_of_nature = { 151802, 37966, 56561, }
TJ.Generated.EquippedMapping.hidden_masters_forbidden_touch = { 137057, }
TJ.Generated.EquippedMapping.koltiras_newfound_will = { 132366, }
TJ.Generated.EquippedMapping.lady_and_the_child = { 144295, }
TJ.Generated.EquippedMapping.luffa_wrappings = { 137056, }
TJ.Generated.EquippedMapping.mantle_of_the_first_kirin_tor = { 151808, }
TJ.Generated.EquippedMapping.mystic_kilt_of_the_rune_master = { 132451, }
TJ.Generated.EquippedMapping.perseverance_of_the_ebon_martyr = { 132459, }
TJ.Generated.EquippedMapping.sephuzs_secret = { 132452, }
TJ.Generated.EquippedMapping.shard_of_the_exodar = { 132410, }
TJ.Generated.EquippedMapping.the_emperors_capacitor = { 144239, }
